apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-coffee-platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: go-coffee-platform
    app.kubernetes.io/part-of: go-coffee
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: go-coffee
  source:
    repoURL: https://github.com/DimaJoyti/go-coffee.git
    targetRevision: main
    path: helm/go-coffee-platform
    helm:
      valueFiles:
        - values.yaml
        - values-production.yaml
      parameters:
        - name: global.environment
          value: production
        - name: global.domain
          value: gocoffee.dev
        - name: services.apiGateway.replicaCount
          value: "3"
        - name: monitoring.prometheus.enabled
          value: "true"
        - name: tracing.jaeger.enabled
          value: "true"
        - name: security.certManager.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: go-coffee
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-coffee-operators
  namespace: argocd
  labels:
    app.kubernetes.io/name: go-coffee-operators
    app.kubernetes.io/part-of: go-coffee
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: go-coffee
  source:
    repoURL: https://github.com/DimaJoyti/go-coffee.git
    targetRevision: main
    path: k8s/operators
  destination:
    server: https://kubernetes.default.svc
    namespace: operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-coffee-monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/name: go-coffee-monitoring
    app.kubernetes.io/part-of: go-coffee
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: go-coffee
  source:
    repoURL: https://github.com/DimaJoyti/go-coffee.git
    targetRevision: main
    path: k8s/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: go-coffee-environments
  namespace: argocd
  labels:
    app.kubernetes.io/name: go-coffee-environments
    app.kubernetes.io/part-of: go-coffee
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          environment: production
  - clusters:
      selector:
        matchLabels:
          environment: staging
  - clusters:
      selector:
        matchLabels:
          environment: development
  template:
    metadata:
      name: 'go-coffee-{{name}}'
      labels:
        app.kubernetes.io/name: 'go-coffee-{{name}}'
        app.kubernetes.io/part-of: go-coffee
        environment: '{{metadata.labels.environment}}'
    spec:
      project: go-coffee
      source:
        repoURL: https://github.com/DimaJoyti/go-coffee.git
        targetRevision: '{{metadata.labels.branch}}'
        path: helm/go-coffee-platform
        helm:
          valueFiles:
            - values.yaml
            - 'values-{{metadata.labels.environment}}.yaml'
          parameters:
            - name: global.environment
              value: '{{metadata.labels.environment}}'
            - name: global.domain
              value: '{{metadata.labels.domain}}'
      destination:
        server: '{{server}}'
        namespace: go-coffee
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: go-coffee
  namespace: argocd
  labels:
    app.kubernetes.io/name: go-coffee-project
    app.kubernetes.io/part-of: go-coffee
spec:
  description: Go Coffee Platform Project
  sourceRepos:
    - 'https://github.com/DimaJoyti/go-coffee.git'
    - 'https://charts.bitnami.com/bitnami'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://grafana.github.io/helm-charts'
    - 'https://jaegertracing.github.io/helm-charts'
    - 'https://helm.elastic.co'
    - 'https://fluent.github.io/helm-charts'
    - 'https://istio-release.storage.googleapis.com/charts'
    - 'https://charts.jetstack.io'
  destinations:
    - namespace: 'go-coffee*'
      server: '*'
    - namespace: 'operators*'
      server: '*'
    - namespace: 'monitoring*'
      server: '*'
    - namespace: 'observability*'
      server: '*'
    - namespace: 'istio-system'
      server: '*'
    - namespace: 'cert-manager'
      server: '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'admissionregistration.k8s.io'
      kind: ValidatingAdmissionWebhook
    - group: 'admissionregistration.k8s.io'
      kind: MutatingAdmissionWebhook
    - group: 'cert-manager.io'
      kind: ClusterIssuer
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
    - group: 'extensions'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
    - group: 'autoscaling'
      kind: '*'
    - group: 'policy'
      kind: '*'
    - group: 'monitoring.coreos.com'
      kind: '*'
    - group: 'jaegertracing.io'
      kind: '*'
    - group: 'coffee.gocoffee.dev'
      kind: '*'
    - group: 'ai.gocoffee.dev'
      kind: '*'
    - group: 'tenant.gocoffee.dev'
      kind: '*'
    - group: 'observability.gocoffee.dev'
      kind: '*'
  roles:
    - name: admin
      description: Admin access to Go Coffee project
      policies:
        - p, proj:go-coffee:admin, applications, *, go-coffee/*, allow
        - p, proj:go-coffee:admin, repositories, *, *, allow
        - p, proj:go-coffee:admin, clusters, *, *, allow
      groups:
        - go-coffee:admins
    - name: developer
      description: Developer access to Go Coffee project
      policies:
        - p, proj:go-coffee:developer, applications, get, go-coffee/*, allow
        - p, proj:go-coffee:developer, applications, sync, go-coffee/*, allow
        - p, proj:go-coffee:developer, repositories, get, *, allow
      groups:
        - go-coffee:developers
    - name: readonly
      description: Read-only access to Go Coffee project
      policies:
        - p, proj:go-coffee:readonly, applications, get, go-coffee/*, allow
        - p, proj:go-coffee:readonly, repositories, get, *, allow
      groups:
        - go-coffee:viewers
