// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: contract.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Contract represents a smart contract
type Contract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Chain         string                 `protobuf:"bytes,5,opt,name=chain,proto3" json:"chain,omitempty"`
	Abi           string                 `protobuf:"bytes,6,opt,name=abi,proto3" json:"abi,omitempty"`
	Bytecode      string                 `protobuf:"bytes,7,opt,name=bytecode,proto3" json:"bytecode,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contract) Reset() {
	*x = Contract{}
	mi := &file_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contract) ProtoMessage() {}

func (x *Contract) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contract.ProtoReflect.Descriptor instead.
func (*Contract) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{0}
}

func (x *Contract) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contract) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Contract) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contract) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Contract) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *Contract) GetAbi() string {
	if x != nil {
		return x.Abi
	}
	return ""
}

func (x *Contract) GetBytecode() string {
	if x != nil {
		return x.Bytecode
	}
	return ""
}

func (x *Contract) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Contract) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// DeployContractRequest represents a request to deploy a contract
type DeployContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Chain         string                 `protobuf:"bytes,4,opt,name=chain,proto3" json:"chain,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Abi           string                 `protobuf:"bytes,6,opt,name=abi,proto3" json:"abi,omitempty"`
	Bytecode      string                 `protobuf:"bytes,7,opt,name=bytecode,proto3" json:"bytecode,omitempty"`
	Arguments     []string               `protobuf:"bytes,8,rep,name=arguments,proto3" json:"arguments,omitempty"`
	Gas           uint64                 `protobuf:"varint,9,opt,name=gas,proto3" json:"gas,omitempty"`
	GasPrice      string                 `protobuf:"bytes,10,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	Passphrase    string                 `protobuf:"bytes,11,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployContractRequest) Reset() {
	*x = DeployContractRequest{}
	mi := &file_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployContractRequest) ProtoMessage() {}

func (x *DeployContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployContractRequest.ProtoReflect.Descriptor instead.
func (*DeployContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{1}
}

func (x *DeployContractRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeployContractRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *DeployContractRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployContractRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *DeployContractRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DeployContractRequest) GetAbi() string {
	if x != nil {
		return x.Abi
	}
	return ""
}

func (x *DeployContractRequest) GetBytecode() string {
	if x != nil {
		return x.Bytecode
	}
	return ""
}

func (x *DeployContractRequest) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *DeployContractRequest) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *DeployContractRequest) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *DeployContractRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

// DeployContractResponse represents a response to a deploy contract request
type DeployContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      *Contract              `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Transaction   *Transaction           `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployContractResponse) Reset() {
	*x = DeployContractResponse{}
	mi := &file_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployContractResponse) ProtoMessage() {}

func (x *DeployContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployContractResponse.ProtoReflect.Descriptor instead.
func (*DeployContractResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{2}
}

func (x *DeployContractResponse) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *DeployContractResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// Transaction represents a blockchain transaction (simplified for this service)
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Gas           uint64                 `protobuf:"varint,6,opt,name=gas,proto3" json:"gas,omitempty"`
	GasPrice      string                 `protobuf:"bytes,7,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{3}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Transaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Transaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transaction) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Transaction) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *Transaction) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ImportContractRequest represents a request to import a contract
type ImportContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Chain         string                 `protobuf:"bytes,4,opt,name=chain,proto3" json:"chain,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Abi           string                 `protobuf:"bytes,6,opt,name=abi,proto3" json:"abi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportContractRequest) Reset() {
	*x = ImportContractRequest{}
	mi := &file_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportContractRequest) ProtoMessage() {}

func (x *ImportContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportContractRequest.ProtoReflect.Descriptor instead.
func (*ImportContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{4}
}

func (x *ImportContractRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ImportContractRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImportContractRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ImportContractRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *ImportContractRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ImportContractRequest) GetAbi() string {
	if x != nil {
		return x.Abi
	}
	return ""
}

// ImportContractResponse represents a response to an import contract request
type ImportContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      *Contract              `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportContractResponse) Reset() {
	*x = ImportContractResponse{}
	mi := &file_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportContractResponse) ProtoMessage() {}

func (x *ImportContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportContractResponse.ProtoReflect.Descriptor instead.
func (*ImportContractResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{5}
}

func (x *ImportContractResponse) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

// GetContractRequest represents a request to get a contract
type GetContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractRequest) Reset() {
	*x = GetContractRequest{}
	mi := &file_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractRequest) ProtoMessage() {}

func (x *GetContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractRequest.ProtoReflect.Descriptor instead.
func (*GetContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{6}
}

func (x *GetContractRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetContractResponse represents a response to a get contract request
type GetContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      *Contract              `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractResponse) Reset() {
	*x = GetContractResponse{}
	mi := &file_contract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractResponse) ProtoMessage() {}

func (x *GetContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractResponse.ProtoReflect.Descriptor instead.
func (*GetContractResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{7}
}

func (x *GetContractResponse) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

// GetContractByAddressRequest represents a request to get a contract by address
type GetContractByAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractByAddressRequest) Reset() {
	*x = GetContractByAddressRequest{}
	mi := &file_contract_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractByAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractByAddressRequest) ProtoMessage() {}

func (x *GetContractByAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractByAddressRequest.ProtoReflect.Descriptor instead.
func (*GetContractByAddressRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{8}
}

func (x *GetContractByAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetContractByAddressRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

// GetContractByAddressResponse represents a response to a get contract by address request
type GetContractByAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      *Contract              `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractByAddressResponse) Reset() {
	*x = GetContractByAddressResponse{}
	mi := &file_contract_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractByAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractByAddressResponse) ProtoMessage() {}

func (x *GetContractByAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractByAddressResponse.ProtoReflect.Descriptor instead.
func (*GetContractByAddressResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{9}
}

func (x *GetContractByAddressResponse) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

// ListContractsRequest represents a request to list contracts
type ListContractsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContractsRequest) Reset() {
	*x = ListContractsRequest{}
	mi := &file_contract_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContractsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContractsRequest) ProtoMessage() {}

func (x *ListContractsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContractsRequest.ProtoReflect.Descriptor instead.
func (*ListContractsRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{10}
}

func (x *ListContractsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListContractsRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *ListContractsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListContractsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListContractsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ListContractsResponse represents a response to a list contracts request
type ListContractsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contracts     []*Contract            `protobuf:"bytes,1,rep,name=contracts,proto3" json:"contracts,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContractsResponse) Reset() {
	*x = ListContractsResponse{}
	mi := &file_contract_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContractsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContractsResponse) ProtoMessage() {}

func (x *ListContractsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContractsResponse.ProtoReflect.Descriptor instead.
func (*ListContractsResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{11}
}

func (x *ListContractsResponse) GetContracts() []*Contract {
	if x != nil {
		return x.Contracts
	}
	return nil
}

func (x *ListContractsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// CallContractRequest represents a request to call a contract method
type CallContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Arguments     []string               `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	From          string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallContractRequest) Reset() {
	*x = CallContractRequest{}
	mi := &file_contract_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallContractRequest) ProtoMessage() {}

func (x *CallContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallContractRequest.ProtoReflect.Descriptor instead.
func (*CallContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{12}
}

func (x *CallContractRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *CallContractRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallContractRequest) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *CallContractRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

// CallContractResponse represents a response to a call contract method request
type CallContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *structpb.Value        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallContractResponse) Reset() {
	*x = CallContractResponse{}
	mi := &file_contract_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallContractResponse) ProtoMessage() {}

func (x *CallContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallContractResponse.ProtoReflect.Descriptor instead.
func (*CallContractResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{13}
}

func (x *CallContractResponse) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

// SendContractTransactionRequest represents a request to send a contract transaction
type SendContractTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Arguments     []string               `protobuf:"bytes,4,rep,name=arguments,proto3" json:"arguments,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Gas           uint64                 `protobuf:"varint,6,opt,name=gas,proto3" json:"gas,omitempty"`
	GasPrice      string                 `protobuf:"bytes,7,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	Passphrase    string                 `protobuf:"bytes,8,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendContractTransactionRequest) Reset() {
	*x = SendContractTransactionRequest{}
	mi := &file_contract_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendContractTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendContractTransactionRequest) ProtoMessage() {}

func (x *SendContractTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendContractTransactionRequest.ProtoReflect.Descriptor instead.
func (*SendContractTransactionRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{14}
}

func (x *SendContractTransactionRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *SendContractTransactionRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *SendContractTransactionRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SendContractTransactionRequest) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *SendContractTransactionRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SendContractTransactionRequest) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *SendContractTransactionRequest) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *SendContractTransactionRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

// SendContractTransactionResponse represents a response to a send contract transaction request
type SendContractTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendContractTransactionResponse) Reset() {
	*x = SendContractTransactionResponse{}
	mi := &file_contract_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendContractTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendContractTransactionResponse) ProtoMessage() {}

func (x *SendContractTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendContractTransactionResponse.ProtoReflect.Descriptor instead.
func (*SendContractTransactionResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{15}
}

func (x *SendContractTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// ContractEvent represents a contract event
type ContractEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	LogIndex      uint32                 `protobuf:"varint,5,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractEvent) Reset() {
	*x = ContractEvent{}
	mi := &file_contract_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractEvent) ProtoMessage() {}

func (x *ContractEvent) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractEvent.ProtoReflect.Descriptor instead.
func (*ContractEvent) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{16}
}

func (x *ContractEvent) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ContractEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *ContractEvent) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ContractEvent) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ContractEvent) GetLogIndex() uint32 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *ContractEvent) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ContractEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetContractEventsRequest represents a request to get contract events
type GetContractEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	FromBlock     uint64                 `protobuf:"varint,3,opt,name=from_block,json=fromBlock,proto3" json:"from_block,omitempty"`
	ToBlock       uint64                 `protobuf:"varint,4,opt,name=to_block,json=toBlock,proto3" json:"to_block,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractEventsRequest) Reset() {
	*x = GetContractEventsRequest{}
	mi := &file_contract_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractEventsRequest) ProtoMessage() {}

func (x *GetContractEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractEventsRequest.ProtoReflect.Descriptor instead.
func (*GetContractEventsRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{17}
}

func (x *GetContractEventsRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *GetContractEventsRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *GetContractEventsRequest) GetFromBlock() uint64 {
	if x != nil {
		return x.FromBlock
	}
	return 0
}

func (x *GetContractEventsRequest) GetToBlock() uint64 {
	if x != nil {
		return x.ToBlock
	}
	return 0
}

func (x *GetContractEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetContractEventsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// GetContractEventsResponse represents a response to a get contract events request
type GetContractEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ContractEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractEventsResponse) Reset() {
	*x = GetContractEventsResponse{}
	mi := &file_contract_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractEventsResponse) ProtoMessage() {}

func (x *GetContractEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractEventsResponse.ProtoReflect.Descriptor instead.
func (*GetContractEventsResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{18}
}

func (x *GetContractEventsResponse) GetEvents() []*ContractEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetContractEventsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// GetTokenInfoRequest represents a request to get token information
type GetTokenInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenInfoRequest) Reset() {
	*x = GetTokenInfoRequest{}
	mi := &file_contract_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenInfoRequest) ProtoMessage() {}

func (x *GetTokenInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenInfoRequest.ProtoReflect.Descriptor instead.
func (*GetTokenInfoRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{19}
}

func (x *GetTokenInfoRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetTokenInfoRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

// GetTokenInfoResponse represents a response to a get token information request
type GetTokenInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals      int32                  `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	TotalSupply   string                 `protobuf:"bytes,4,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenInfoResponse) Reset() {
	*x = GetTokenInfoResponse{}
	mi := &file_contract_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenInfoResponse) ProtoMessage() {}

func (x *GetTokenInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenInfoResponse.ProtoReflect.Descriptor instead.
func (*GetTokenInfoResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{20}
}

func (x *GetTokenInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTokenInfoResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTokenInfoResponse) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *GetTokenInfoResponse) GetTotalSupply() string {
	if x != nil {
		return x.TotalSupply
	}
	return ""
}

func (x *GetTokenInfoResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_contract_proto protoreflect.FileDescriptor

const file_contract_proto_rawDesc = "" +
	"\n" +
	"\x0econtract.proto\x12\bcontract\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x9b\x02\n" +
	"\bContract\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x14\n" +
	"\x05chain\x18\x05 \x01(\tR\x05chain\x12\x10\n" +
	"\x03abi\x18\x06 \x01(\tR\x03abi\x12\x1a\n" +
	"\bbytecode\x18\a \x01(\tR\bbytecode\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa6\x02\n" +
	"\x15DeployContractRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05chain\x18\x04 \x01(\tR\x05chain\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x10\n" +
	"\x03abi\x18\x06 \x01(\tR\x03abi\x12\x1a\n" +
	"\bbytecode\x18\a \x01(\tR\bbytecode\x12\x1c\n" +
	"\targuments\x18\b \x03(\tR\targuments\x12\x10\n" +
	"\x03gas\x18\t \x01(\x04R\x03gas\x12\x1b\n" +
	"\tgas_price\x18\n" +
	" \x01(\tR\bgasPrice\x12\x1e\n" +
	"\n" +
	"passphrase\x18\v \x01(\tR\n" +
	"passphrase\"\x81\x01\n" +
	"\x16DeployContractResponse\x12.\n" +
	"\bcontract\x18\x01 \x01(\v2\x12.contract.ContractR\bcontract\x127\n" +
	"\vtransaction\x18\x02 \x01(\v2\x15.contract.TransactionR\vtransaction\"\xb2\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12\x10\n" +
	"\x03gas\x18\x06 \x01(\x04R\x03gas\x12\x1b\n" +
	"\tgas_price\x18\a \x01(\tR\bgasPrice\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"\x9a\x01\n" +
	"\x15ImportContractRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x14\n" +
	"\x05chain\x18\x04 \x01(\tR\x05chain\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x10\n" +
	"\x03abi\x18\x06 \x01(\tR\x03abi\"H\n" +
	"\x16ImportContractResponse\x12.\n" +
	"\bcontract\x18\x01 \x01(\v2\x12.contract.ContractR\bcontract\"$\n" +
	"\x12GetContractRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x13GetContractResponse\x12.\n" +
	"\bcontract\x18\x01 \x01(\v2\x12.contract.ContractR\bcontract\"M\n" +
	"\x1bGetContractByAddressRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\"N\n" +
	"\x1cGetContractByAddressResponse\x12.\n" +
	"\bcontract\x18\x01 \x01(\v2\x12.contract.ContractR\bcontract\"\x87\x01\n" +
	"\x14ListContractsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"_\n" +
	"\x15ListContractsResponse\x120\n" +
	"\tcontracts\x18\x01 \x03(\v2\x12.contract.ContractR\tcontracts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x80\x01\n" +
	"\x13CallContractRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x1c\n" +
	"\targuments\x18\x03 \x03(\tR\targuments\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\"F\n" +
	"\x14CallContractResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x06result\"\xf9\x01\n" +
	"\x1eSendContractTransactionRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x1c\n" +
	"\targuments\x18\x04 \x03(\tR\targuments\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12\x10\n" +
	"\x03gas\x18\x06 \x01(\x04R\x03gas\x12\x1b\n" +
	"\tgas_price\x18\a \x01(\tR\bgasPrice\x12\x1e\n" +
	"\n" +
	"passphrase\x18\b \x01(\tR\n" +
	"passphrase\"Z\n" +
	"\x1fSendContractTransactionResponse\x127\n" +
	"\vtransaction\x18\x01 \x01(\v2\x15.contract.TransactionR\vtransaction\"\x95\x02\n" +
	"\rContractEvent\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12!\n" +
	"\fblock_number\x18\x04 \x01(\x04R\vblockNumber\x12\x1b\n" +
	"\tlog_index\x18\x05 \x01(\rR\blogIndex\x12+\n" +
	"\x04data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04data\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb9\x01\n" +
	"\x18GetContractEventsRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x1d\n" +
	"\n" +
	"from_block\x18\x03 \x01(\x04R\tfromBlock\x12\x19\n" +
	"\bto_block\x18\x04 \x01(\x04R\atoBlock\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"b\n" +
	"\x19GetContractEventsResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.contract.ContractEventR\x06events\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"E\n" +
	"\x13GetTokenInfoRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\"\x95\x01\n" +
	"\x14GetTokenInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bdecimals\x18\x03 \x01(\x05R\bdecimals\x12!\n" +
	"\ftotal_supply\x18\x04 \x01(\tR\vtotalSupply\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type2\xc3\x06\n" +
	"\x14SmartContractService\x12U\n" +
	"\x0eDeployContract\x12\x1f.contract.DeployContractRequest\x1a .contract.DeployContractResponse\"\x00\x12U\n" +
	"\x0eImportContract\x12\x1f.contract.ImportContractRequest\x1a .contract.ImportContractResponse\"\x00\x12L\n" +
	"\vGetContract\x12\x1c.contract.GetContractRequest\x1a\x1d.contract.GetContractResponse\"\x00\x12g\n" +
	"\x14GetContractByAddress\x12%.contract.GetContractByAddressRequest\x1a&.contract.GetContractByAddressResponse\"\x00\x12R\n" +
	"\rListContracts\x12\x1e.contract.ListContractsRequest\x1a\x1f.contract.ListContractsResponse\"\x00\x12O\n" +
	"\fCallContract\x12\x1d.contract.CallContractRequest\x1a\x1e.contract.CallContractResponse\"\x00\x12p\n" +
	"\x17SendContractTransaction\x12(.contract.SendContractTransactionRequest\x1a).contract.SendContractTransactionResponse\"\x00\x12^\n" +
	"\x11GetContractEvents\x12\".contract.GetContractEventsRequest\x1a#.contract.GetContractEventsResponse\"\x00\x12O\n" +
	"\fGetTokenInfo\x12\x1d.contract.GetTokenInfoRequest\x1a\x1e.contract.GetTokenInfoResponse\"\x00BGZEgithub.com/DimaJoyti/go-coffee/web3-wallet-backend/api/proto/contractb\x06proto3"

var (
	file_contract_proto_rawDescOnce sync.Once
	file_contract_proto_rawDescData []byte
)

func file_contract_proto_rawDescGZIP() []byte {
	file_contract_proto_rawDescOnce.Do(func() {
		file_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)))
	})
	return file_contract_proto_rawDescData
}

var file_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_contract_proto_goTypes = []any{
	(*Contract)(nil),                        // 0: contract.Contract
	(*DeployContractRequest)(nil),           // 1: contract.DeployContractRequest
	(*DeployContractResponse)(nil),          // 2: contract.DeployContractResponse
	(*Transaction)(nil),                     // 3: contract.Transaction
	(*ImportContractRequest)(nil),           // 4: contract.ImportContractRequest
	(*ImportContractResponse)(nil),          // 5: contract.ImportContractResponse
	(*GetContractRequest)(nil),              // 6: contract.GetContractRequest
	(*GetContractResponse)(nil),             // 7: contract.GetContractResponse
	(*GetContractByAddressRequest)(nil),     // 8: contract.GetContractByAddressRequest
	(*GetContractByAddressResponse)(nil),    // 9: contract.GetContractByAddressResponse
	(*ListContractsRequest)(nil),            // 10: contract.ListContractsRequest
	(*ListContractsResponse)(nil),           // 11: contract.ListContractsResponse
	(*CallContractRequest)(nil),             // 12: contract.CallContractRequest
	(*CallContractResponse)(nil),            // 13: contract.CallContractResponse
	(*SendContractTransactionRequest)(nil),  // 14: contract.SendContractTransactionRequest
	(*SendContractTransactionResponse)(nil), // 15: contract.SendContractTransactionResponse
	(*ContractEvent)(nil),                   // 16: contract.ContractEvent
	(*GetContractEventsRequest)(nil),        // 17: contract.GetContractEventsRequest
	(*GetContractEventsResponse)(nil),       // 18: contract.GetContractEventsResponse
	(*GetTokenInfoRequest)(nil),             // 19: contract.GetTokenInfoRequest
	(*GetTokenInfoResponse)(nil),            // 20: contract.GetTokenInfoResponse
	(*timestamppb.Timestamp)(nil),           // 21: google.protobuf.Timestamp
	(*structpb.Value)(nil),                  // 22: google.protobuf.Value
	(*structpb.Struct)(nil),                 // 23: google.protobuf.Struct
}
var file_contract_proto_depIdxs = []int32{
	21, // 0: contract.Contract.created_at:type_name -> google.protobuf.Timestamp
	21, // 1: contract.Contract.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: contract.DeployContractResponse.contract:type_name -> contract.Contract
	3,  // 3: contract.DeployContractResponse.transaction:type_name -> contract.Transaction
	0,  // 4: contract.ImportContractResponse.contract:type_name -> contract.Contract
	0,  // 5: contract.GetContractResponse.contract:type_name -> contract.Contract
	0,  // 6: contract.GetContractByAddressResponse.contract:type_name -> contract.Contract
	0,  // 7: contract.ListContractsResponse.contracts:type_name -> contract.Contract
	22, // 8: contract.CallContractResponse.result:type_name -> google.protobuf.Value
	3,  // 9: contract.SendContractTransactionResponse.transaction:type_name -> contract.Transaction
	23, // 10: contract.ContractEvent.data:type_name -> google.protobuf.Struct
	21, // 11: contract.ContractEvent.created_at:type_name -> google.protobuf.Timestamp
	16, // 12: contract.GetContractEventsResponse.events:type_name -> contract.ContractEvent
	1,  // 13: contract.SmartContractService.DeployContract:input_type -> contract.DeployContractRequest
	4,  // 14: contract.SmartContractService.ImportContract:input_type -> contract.ImportContractRequest
	6,  // 15: contract.SmartContractService.GetContract:input_type -> contract.GetContractRequest
	8,  // 16: contract.SmartContractService.GetContractByAddress:input_type -> contract.GetContractByAddressRequest
	10, // 17: contract.SmartContractService.ListContracts:input_type -> contract.ListContractsRequest
	12, // 18: contract.SmartContractService.CallContract:input_type -> contract.CallContractRequest
	14, // 19: contract.SmartContractService.SendContractTransaction:input_type -> contract.SendContractTransactionRequest
	17, // 20: contract.SmartContractService.GetContractEvents:input_type -> contract.GetContractEventsRequest
	19, // 21: contract.SmartContractService.GetTokenInfo:input_type -> contract.GetTokenInfoRequest
	2,  // 22: contract.SmartContractService.DeployContract:output_type -> contract.DeployContractResponse
	5,  // 23: contract.SmartContractService.ImportContract:output_type -> contract.ImportContractResponse
	7,  // 24: contract.SmartContractService.GetContract:output_type -> contract.GetContractResponse
	9,  // 25: contract.SmartContractService.GetContractByAddress:output_type -> contract.GetContractByAddressResponse
	11, // 26: contract.SmartContractService.ListContracts:output_type -> contract.ListContractsResponse
	13, // 27: contract.SmartContractService.CallContract:output_type -> contract.CallContractResponse
	15, // 28: contract.SmartContractService.SendContractTransaction:output_type -> contract.SendContractTransactionResponse
	18, // 29: contract.SmartContractService.GetContractEvents:output_type -> contract.GetContractEventsResponse
	20, // 30: contract.SmartContractService.GetTokenInfo:output_type -> contract.GetTokenInfoResponse
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_contract_proto_init() }
func file_contract_proto_init() {
	if File_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_proto_goTypes,
		DependencyIndexes: file_contract_proto_depIdxs,
		MessageInfos:      file_contract_proto_msgTypes,
	}.Build()
	File_contract_proto = out.File
	file_contract_proto_goTypes = nil
	file_contract_proto_depIdxs = nil
}
