apiVersion: v1
kind: Namespace
metadata:
  name: go-coffee-platform
  labels:
    name: go-coffee-platform
    app.kubernetes.io/name: go-coffee
    app.kubernetes.io/part-of: go-coffee-platform
    app.kubernetes.io/version: "2.0.0"
    environment: production
    tier: platform
  annotations:
    description: "Go Coffee Platform - AI-Powered Coffee Business Automation"
    contact: "platform-team@go-coffee.com"
    documentation: "https://docs.go-coffee.com"
---
apiVersion: v1
kind: Namespace
metadata:
  name: go-coffee-monitoring
  labels:
    name: go-coffee-monitoring
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: go-coffee-platform
    app.kubernetes.io/version: "2.0.0"
    environment: production
    tier: monitoring
  annotations:
    description: "Go Coffee Platform - Monitoring and Observability"
---
apiVersion: v1
kind: Namespace
metadata:
  name: go-coffee-security
  labels:
    name: go-coffee-security
    app.kubernetes.io/name: security
    app.kubernetes.io/part-of: go-coffee-platform
    app.kubernetes.io/version: "2.0.0"
    environment: production
    tier: security
  annotations:
    description: "Go Coffee Platform - Security and Compliance"
---
# Network Policies for namespace isolation
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: go-coffee-platform-network-policy
  namespace: go-coffee-platform
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: go-coffee-platform
    - namespaceSelector:
        matchLabels:
          name: go-coffee-monitoring
    - namespaceSelector:
        matchLabels:
          name: istio-system
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: go-coffee-platform
    - namespaceSelector:
        matchLabels:
          name: go-coffee-monitoring
    - namespaceSelector:
        matchLabels:
          name: kube-system
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
---
# Resource Quotas
apiVersion: v1
kind: ResourceQuota
metadata:
  name: go-coffee-platform-quota
  namespace: go-coffee-platform
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "20"
    services: "50"
    secrets: "20"
    configmaps: "20"
    pods: "100"
---
# Limit Ranges
apiVersion: v1
kind: LimitRange
metadata:
  name: go-coffee-platform-limits
  namespace: go-coffee-platform
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "128Mi"
    type: Container
  - max:
      storage: "100Gi"
    min:
      storage: "1Gi"
    type: PersistentVolumeClaim
