{{- if .Values.services.apiGateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-coffee-platform.deploymentName" (dict "component" "api-gateway" "Values" .Values "Chart" .Chart "Release" .Release) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-coffee-platform.serviceLabels" (dict "component" "api-gateway" "Values" .Values "Chart" .Chart "Release" .Release) | nindent 4 }}
spec:
  replicas: {{ .Values.services.apiGateway.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "go-coffee-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api-gateway
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- include "go-coffee-platform.istioAnnotations" . | nindent 8 }}
        {{- with .Values.services.apiGateway.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "go-coffee-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api-gateway
        version: {{ .Chart.AppVersion }}
    spec:
      {{- include "go-coffee-platform.podSecurityContext" . | nindent 6 }}
      serviceAccountName: {{ include "go-coffee-platform.serviceAccountName" . }}
      {{- with .Values.services.apiGateway.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: api-gateway
        image: "{{ .Values.services.apiGateway.image.repository }}:{{ .Values.services.apiGateway.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.services.apiGateway.image.pullPolicy }}
        {{- include "go-coffee-platform.securityContext" . | nindent 8 }}
        ports:
        - name: http
          containerPort: {{ .Values.services.apiGateway.port }}
          protocol: TCP
        - name: grpc
          containerPort: {{ .Values.services.apiGateway.grpcPort | default 50051 }}
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        {{- include "go-coffee-platform.commonEnv" . | nindent 8 }}
        {{- include "go-coffee-platform.databaseEnv" . | nindent 8 }}
        {{- include "go-coffee-platform.redisEnv" . | nindent 8 }}
        {{- include "go-coffee-platform.kafkaEnv" . | nindent 8 }}
        - name: SERVER_PORT
          value: {{ .Values.services.apiGateway.port | quote }}
        - name: GRPC_PORT
          value: {{ .Values.services.apiGateway.grpcPort | default 50051 | quote }}
        - name: ORDER_SERVICE_URL
          value: "{{ include "go-coffee-platform.serviceName" (dict "component" "order-service" "Values" .Values "Chart" .Chart "Release" .Release) }}:{{ .Values.services.orderService.port }}"
        - name: PAYMENT_SERVICE_URL
          value: "{{ include "go-coffee-platform.serviceName" (dict "component" "payment-service" "Values" .Values "Chart" .Chart "Release" .Release) }}:{{ .Values.services.paymentService.port }}"
        - name: KITCHEN_SERVICE_URL
          value: "{{ include "go-coffee-platform.serviceName" (dict "component" "kitchen-service" "Values" .Values "Chart" .Chart "Release" .Release) }}:{{ .Values.services.kitchenService.port }}"
        {{- with .Values.services.apiGateway.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "go-coffee-platform.livenessProbe" . | nindent 8 }}
        {{- include "go-coffee-platform.readinessProbe" . | nindent 8 }}
        {{- include "go-coffee-platform.startupProbe" . | nindent 8 }}
        {{- include "go-coffee-platform.resources" .Values.services.apiGateway | nindent 8 }}
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/cache
        {{- if .Values.global.tls.enabled }}
        - name: tls-certs
          mountPath: /app/certs
          readOnly: true
        {{- end }}
      {{- if .Values.services.apiGateway.sidecar.enabled }}
      - name: {{ .Values.services.apiGateway.sidecar.name }}
        image: "{{ .Values.services.apiGateway.sidecar.image.repository }}:{{ .Values.services.apiGateway.sidecar.image.tag }}"
        imagePullPolicy: {{ .Values.services.apiGateway.sidecar.image.pullPolicy }}
        {{- with .Values.services.apiGateway.sidecar.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "go-coffee-platform.fullname" . }}-config
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      {{- if .Values.global.tls.enabled }}
      - name: tls-certs
        secret:
          secretName: {{ .Values.global.tls.secretName }}
      {{- end }}
      {{- with .Values.services.apiGateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.apiGateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.apiGateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.services.apiGateway.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range .Values.services.apiGateway.topologySpreadConstraints }}
        - maxSkew: {{ .maxSkew }}
          topologyKey: {{ .topologyKey }}
          whenUnsatisfiable: {{ .whenUnsatisfiable }}
          labelSelector:
            matchLabels:
              {{- include "go-coffee-platform.selectorLabels" $ | nindent 14 }}
              app.kubernetes.io/component: api-gateway
        {{- end }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-coffee-platform.serviceName" (dict "component" "api-gateway" "Values" .Values "Chart" .Chart "Release" .Release) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-coffee-platform.serviceLabels" (dict "component" "api-gateway" "Values" .Values "Chart" .Chart "Release" .Release) | nindent 4 }}
  {{- with .Values.services.apiGateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.apiGateway.service.type }}
  {{- if eq .Values.services.apiGateway.service.type "LoadBalancer" }}
  {{- with .Values.services.apiGateway.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.services.apiGateway.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
  - port: {{ .Values.services.apiGateway.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.services.apiGateway.service.grpcPort | default 50051 }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: 9090
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "go-coffee-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
{{- end }}
