apiVersion: v1
kind: ConfigMap
metadata:
  name: go-coffee-config
  namespace: go-coffee
  labels:
    app.kubernetes.io/name: go-coffee
    app.kubernetes.io/component: config
data:
  # Environment Configuration
  ENVIRONMENT: "production"
  SERVICE_NAME: "go-coffee"
  SERVICE_VERSION: "1.0.0"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"

  # Database Configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "go_coffee"
  DB_USER: "go_coffee_user"
  DB_SSL_MODE: "require"
  DB_MAX_OPEN_CONNS: "50"
  DB_MAX_IDLE_CONNS: "10"
  DB_CONN_MAX_LIFETIME: "5m"
  DB_CONN_MAX_IDLE_TIME: "1m"

  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_POOL_SIZE: "50"
  REDIS_MIN_IDLE_CONNS: "10"
  REDIS_MAX_RETRIES: "5"
  REDIS_DIAL_TIMEOUT: "5s"
  REDIS_READ_TIMEOUT: "3s"
  REDIS_WRITE_TIMEOUT: "3s"
  REDIS_IDLE_TIMEOUT: "5m"

  # HTTP Server Configuration
  HTTP_HOST: "0.0.0.0"
  HTTP_PORT: "8080"
  HTTP_READ_TIMEOUT: "15s"
  HTTP_WRITE_TIMEOUT: "15s"
  HTTP_IDLE_TIMEOUT: "60s"
  HTTP_MAX_HEADER_BYTES: "1048576"

  # JWT Configuration
  JWT_ACCESS_TOKEN_TTL: "5m"
  JWT_REFRESH_TOKEN_TTL: "7d"
  JWT_ISSUER: "go-coffee"
  JWT_AUDIENCE: "go-coffee-users"
  JWT_ALGORITHM: "HS256"
  JWT_REFRESH_THRESHOLD: "5m"

  # Session Configuration
  SESSION_COOKIE_NAME: "go_coffee_session"
  SESSION_COOKIE_DOMAIN: ".go-coffee.com"
  SESSION_COOKIE_PATH: "/"
  SESSION_COOKIE_SECURE: "true"
  SESSION_COOKIE_HTTP_ONLY: "true"
  SESSION_COOKIE_SAME_SITE: "Strict"
  SESSION_MAX_AGE: "24h"
  SESSION_IDLE_TIMEOUT: "30m"

  # Rate Limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS_PER_MINUTE: "1000"
  RATE_LIMIT_BURST_SIZE: "50"
  RATE_LIMIT_WINDOW_SIZE: "1m"
  RATE_LIMIT_CLEANUP_INTERVAL: "5m"

  # Monitoring Configuration
  METRICS_ENABLED: "true"
  METRICS_PATH: "/metrics"
  METRICS_NAMESPACE: "go_coffee"
  METRICS_SUBSYSTEM: "production"
  METRICS_INTERVAL: "10s"

  HEALTH_ENABLED: "true"
  HEALTH_PATH: "/health"
  HEALTH_TIMEOUT: "5s"
  HEALTH_INTERVAL: "15s"
  HEALTH_FAILURE_THRESHOLD: "3"
  HEALTH_SUCCESS_THRESHOLD: "1"

  # Feature Flags
  FEATURE_EVENT_SOURCING: "true"
  FEATURE_REAL_TIME_SESSIONS: "true"
  FEATURE_ADVANCED_METRICS: "true"
  FEATURE_HEALTH_CHECKS: "true"
  FEATURE_GRACEFUL_SHUTDOWN: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: go-coffee
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
data:
  POSTGRES_DB: "go_coffee"
  POSTGRES_USER: "go_coffee_user"
  PGDATA: "/var/lib/postgresql/data/pgdata"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: go-coffee
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
data:
  redis.conf: |
    # Redis Configuration for Go Coffee Platform
    bind 0.0.0.0
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300

    daemonize no
    supervised no
    loglevel notice
    databases 16

    # Memory Management
    maxmemory 1gb
    maxmemory-policy allkeys-lru
    maxmemory-samples 5

    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes

    # Append Only File
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb

    # Monitoring
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    latency-monitor-threshold 100

    # Event Notifications for Infrastructure
    notify-keyspace-events "Ex"
