apiVersion: v1
kind: Namespace
metadata:
  name: go-coffee
  labels:
    name: go-coffee
    environment: production
    app.kubernetes.io/name: go-coffee
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: go-coffee-platform
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "Go Coffee Platform - Web3 Coffee Ordering Platform"
    contact: "admin@go-coffee.com"
    documentation: "https://docs.go-coffee.com"
---
apiVersion: v1
kind: Namespace
metadata:
  name: go-coffee-staging
  labels:
    name: go-coffee-staging
    environment: staging
    app.kubernetes.io/name: go-coffee
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: go-coffee-platform
    app.kubernetes.io/managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: go-coffee-monitoring
  labels:
    name: go-coffee-monitoring
    environment: production
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: go-coffee-platform
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: go-coffee-quota
  namespace: go-coffee
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: go-coffee-limits
  namespace: go-coffee
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim
