# Enhanced ArgoCD Configuration for Go Coffee Platform
# Comprehensive GitOps setup with multi-environment support

apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: gitops
---
# Go Coffee AppProject
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: go-coffee
  namespace: argocd
  labels:
    app.kubernetes.io/name: go-coffee
    app.kubernetes.io/component: gitops
    app.kubernetes.io/part-of: go-coffee-platform
spec:
  description: Go Coffee Platform Project - Comprehensive microservices deployment
  sourceRepos:
  - 'https://github.com/DimaJoyti/go-coffee.git'
  - 'https://charts.bitnami.com/bitnami'
  - 'https://prometheus-community.github.io/helm-charts'
  - 'https://grafana.github.io/helm-charts'
  destinations:
  - namespace: 'go-coffee-*'
    server: https://kubernetes.default.svc
  - namespace: 'go-coffee-monitoring'
    server: https://kubernetes.default.svc
  - namespace: 'go-coffee-security'
    server: https://kubernetes.default.svc
  - namespace: 'argocd'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: ''
    kind: PersistentVolume
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition
  - group: 'admissionregistration.k8s.io'
    kind: ValidatingAdmissionWebhook
  - group: 'admissionregistration.k8s.io'
    kind: MutatingAdmissionWebhook
  namespaceResourceWhitelist:
  - group: ''
    kind: '*'
  - group: 'apps'
    kind: '*'
  - group: 'extensions'
    kind: '*'
  - group: 'networking.k8s.io'
    kind: '*'
  - group: 'monitoring.coreos.com'
    kind: '*'
  - group: 'policy'
    kind: '*'
  - group: 'autoscaling'
    kind: '*'
  roles:
  - name: admin
    description: Admin access to Go Coffee project
    policies:
    - p, proj:go-coffee:admin, applications, *, go-coffee/*, allow
    - p, proj:go-coffee:admin, repositories, *, *, allow
    - p, proj:go-coffee:admin, clusters, *, *, allow
    - p, proj:go-coffee:admin, logs, get, go-coffee/*, allow
    - p, proj:go-coffee:admin, exec, create, go-coffee/*, allow
    groups:
    - go-coffee:admins
  - name: developer
    description: Developer access to Go Coffee project
    policies:
    - p, proj:go-coffee:developer, applications, get, go-coffee/*, allow
    - p, proj:go-coffee:developer, applications, sync, go-coffee/*, allow
    - p, proj:go-coffee:developer, applications, action/*, go-coffee/*, allow
    - p, proj:go-coffee:developer, logs, get, go-coffee/*, allow
    - p, proj:go-coffee:developer, repositories, get, *, allow
    groups:
    - go-coffee:developers
  - name: viewer
    description: Read-only access to Go Coffee project
    policies:
    - p, proj:go-coffee:viewer, applications, get, go-coffee/*, allow
    - p, proj:go-coffee:viewer, logs, get, go-coffee/*, allow
    groups:
    - go-coffee:viewers
---
# Core Services Application (Staging)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-coffee-core-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: go-coffee
    app.kubernetes.io/component: core
    app.kubernetes.io/part-of: go-coffee-platform
    environment: staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: go-coffee
  source:
    repoURL: https://github.com/DimaJoyti/go-coffee.git
    targetRevision: develop
    path: ci-cd/kubernetes/manifests/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: go-coffee-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/clusterIP
---
# Core Services Application (Production)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-coffee-core-production
  namespace: argocd
  labels:
    app.kubernetes.io/name: go-coffee
    app.kubernetes.io/component: core
    app.kubernetes.io/part-of: go-coffee-platform
    environment: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: go-coffee
  source:
    repoURL: https://github.com/DimaJoyti/go-coffee.git
    targetRevision: main
    path: ci-cd/kubernetes/manifests/production
  destination:
    server: https://kubernetes.default.svc
    namespace: go-coffee-production
  syncPolicy:
    # Manual sync for production
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 20
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/clusterIP
---
# AI Services Application (Staging)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-coffee-ai-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: go-coffee
    app.kubernetes.io/component: ai
    app.kubernetes.io/part-of: go-coffee-platform
    environment: staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: go-coffee
  source:
    repoURL: https://github.com/DimaJoyti/go-coffee.git
    targetRevision: develop
    path: ai-agents
  destination:
    server: https://kubernetes.default.svc
    namespace: go-coffee-ai-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
# AI Services Application (Production)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-coffee-ai-production
  namespace: argocd
  labels:
    app.kubernetes.io/name: go-coffee
    app.kubernetes.io/component: ai
    app.kubernetes.io/part-of: go-coffee-platform
    environment: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: go-coffee
  source:
    repoURL: https://github.com/DimaJoyti/go-coffee.git
    targetRevision: main
    path: ai-agents
  destination:
    server: https://kubernetes.default.svc
    namespace: go-coffee-ai-production
  syncPolicy:
    # Manual sync for production AI services
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 20
---
# Monitoring Stack Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-coffee-monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/name: go-coffee
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: go-coffee-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: go-coffee
  source:
    repoURL: https://github.com/DimaJoyti/go-coffee.git
    targetRevision: main
    path: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: go-coffee-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
# Security Stack Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-coffee-security
  namespace: argocd
  labels:
    app.kubernetes.io/name: go-coffee
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: go-coffee-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: go-coffee
  source:
    repoURL: https://github.com/DimaJoyti/go-coffee.git
    targetRevision: main
    path: security
  destination:
    server: https://kubernetes.default.svc
    namespace: go-coffee-security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
