// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: security.proto

package security

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenerateKeyPairRequest represents a request to generate a key pair
type GenerateKeyPairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKeyPairRequest) Reset() {
	*x = GenerateKeyPairRequest{}
	mi := &file_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyPairRequest) ProtoMessage() {}

func (x *GenerateKeyPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyPairRequest.ProtoReflect.Descriptor instead.
func (*GenerateKeyPairRequest) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateKeyPairRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

// GenerateKeyPairResponse represents a response to a generate key pair request
type GenerateKeyPairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey    string                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKeyPairResponse) Reset() {
	*x = GenerateKeyPairResponse{}
	mi := &file_security_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyPairResponse) ProtoMessage() {}

func (x *GenerateKeyPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyPairResponse.ProtoReflect.Descriptor instead.
func (*GenerateKeyPairResponse) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateKeyPairResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *GenerateKeyPairResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *GenerateKeyPairResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// EncryptPrivateKeyRequest represents a request to encrypt a private key
type EncryptPrivateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey    string                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Passphrase    string                 `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptPrivateKeyRequest) Reset() {
	*x = EncryptPrivateKeyRequest{}
	mi := &file_security_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptPrivateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptPrivateKeyRequest) ProtoMessage() {}

func (x *EncryptPrivateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptPrivateKeyRequest.ProtoReflect.Descriptor instead.
func (*EncryptPrivateKeyRequest) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{2}
}

func (x *EncryptPrivateKeyRequest) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *EncryptPrivateKeyRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

// EncryptPrivateKeyResponse represents a response to an encrypt private key request
type EncryptPrivateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptedKey  string                 `protobuf:"bytes,1,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptPrivateKeyResponse) Reset() {
	*x = EncryptPrivateKeyResponse{}
	mi := &file_security_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptPrivateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptPrivateKeyResponse) ProtoMessage() {}

func (x *EncryptPrivateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptPrivateKeyResponse.ProtoReflect.Descriptor instead.
func (*EncryptPrivateKeyResponse) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{3}
}

func (x *EncryptPrivateKeyResponse) GetEncryptedKey() string {
	if x != nil {
		return x.EncryptedKey
	}
	return ""
}

// DecryptPrivateKeyRequest represents a request to decrypt a private key
type DecryptPrivateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptedKey  string                 `protobuf:"bytes,1,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
	Passphrase    string                 `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptPrivateKeyRequest) Reset() {
	*x = DecryptPrivateKeyRequest{}
	mi := &file_security_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptPrivateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptPrivateKeyRequest) ProtoMessage() {}

func (x *DecryptPrivateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptPrivateKeyRequest.ProtoReflect.Descriptor instead.
func (*DecryptPrivateKeyRequest) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{4}
}

func (x *DecryptPrivateKeyRequest) GetEncryptedKey() string {
	if x != nil {
		return x.EncryptedKey
	}
	return ""
}

func (x *DecryptPrivateKeyRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

// DecryptPrivateKeyResponse represents a response to a decrypt private key request
type DecryptPrivateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey    string                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptPrivateKeyResponse) Reset() {
	*x = DecryptPrivateKeyResponse{}
	mi := &file_security_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptPrivateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptPrivateKeyResponse) ProtoMessage() {}

func (x *DecryptPrivateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptPrivateKeyResponse.ProtoReflect.Descriptor instead.
func (*DecryptPrivateKeyResponse) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{5}
}

func (x *DecryptPrivateKeyResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

// GenerateJWTRequest represents a request to generate a JWT token
type GenerateJWTRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Expiration    int64                  `protobuf:"varint,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateJWTRequest) Reset() {
	*x = GenerateJWTRequest{}
	mi := &file_security_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateJWTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateJWTRequest) ProtoMessage() {}

func (x *GenerateJWTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateJWTRequest.ProtoReflect.Descriptor instead.
func (*GenerateJWTRequest) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateJWTRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateJWTRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GenerateJWTRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GenerateJWTRequest) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

// GenerateJWTResponse represents a response to a generate JWT token request
type GenerateJWTResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateJWTResponse) Reset() {
	*x = GenerateJWTResponse{}
	mi := &file_security_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateJWTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateJWTResponse) ProtoMessage() {}

func (x *GenerateJWTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateJWTResponse.ProtoReflect.Descriptor instead.
func (*GenerateJWTResponse) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateJWTResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GenerateJWTResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *GenerateJWTResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// VerifyJWTRequest represents a request to verify a JWT token
type VerifyJWTRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyJWTRequest) Reset() {
	*x = VerifyJWTRequest{}
	mi := &file_security_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyJWTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyJWTRequest) ProtoMessage() {}

func (x *VerifyJWTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyJWTRequest.ProtoReflect.Descriptor instead.
func (*VerifyJWTRequest) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyJWTRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// VerifyJWTResponse represents a response to a verify JWT token request
type VerifyJWTResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyJWTResponse) Reset() {
	*x = VerifyJWTResponse{}
	mi := &file_security_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyJWTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyJWTResponse) ProtoMessage() {}

func (x *VerifyJWTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyJWTResponse.ProtoReflect.Descriptor instead.
func (*VerifyJWTResponse) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyJWTResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyJWTResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyJWTResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyJWTResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *VerifyJWTResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// GenerateMnemonicRequest represents a request to generate a mnemonic phrase
type GenerateMnemonicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strength      int32                  `protobuf:"varint,1,opt,name=strength,proto3" json:"strength,omitempty"` // 128, 160, 192, 224, or 256 bits
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateMnemonicRequest) Reset() {
	*x = GenerateMnemonicRequest{}
	mi := &file_security_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateMnemonicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMnemonicRequest) ProtoMessage() {}

func (x *GenerateMnemonicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMnemonicRequest.ProtoReflect.Descriptor instead.
func (*GenerateMnemonicRequest) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateMnemonicRequest) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

// GenerateMnemonicResponse represents a response to a generate mnemonic phrase request
type GenerateMnemonicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mnemonic      string                 `protobuf:"bytes,1,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateMnemonicResponse) Reset() {
	*x = GenerateMnemonicResponse{}
	mi := &file_security_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateMnemonicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMnemonicResponse) ProtoMessage() {}

func (x *GenerateMnemonicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMnemonicResponse.ProtoReflect.Descriptor instead.
func (*GenerateMnemonicResponse) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{11}
}

func (x *GenerateMnemonicResponse) GetMnemonic() string {
	if x != nil {
		return x.Mnemonic
	}
	return ""
}

// ValidateMnemonicRequest represents a request to validate a mnemonic phrase
type ValidateMnemonicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mnemonic      string                 `protobuf:"bytes,1,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMnemonicRequest) Reset() {
	*x = ValidateMnemonicRequest{}
	mi := &file_security_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMnemonicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMnemonicRequest) ProtoMessage() {}

func (x *ValidateMnemonicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMnemonicRequest.ProtoReflect.Descriptor instead.
func (*ValidateMnemonicRequest) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{12}
}

func (x *ValidateMnemonicRequest) GetMnemonic() string {
	if x != nil {
		return x.Mnemonic
	}
	return ""
}

// ValidateMnemonicResponse represents a response to a validate mnemonic phrase request
type ValidateMnemonicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMnemonicResponse) Reset() {
	*x = ValidateMnemonicResponse{}
	mi := &file_security_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMnemonicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMnemonicResponse) ProtoMessage() {}

func (x *ValidateMnemonicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMnemonicResponse.ProtoReflect.Descriptor instead.
func (*ValidateMnemonicResponse) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{13}
}

func (x *ValidateMnemonicResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// MnemonicToPrivateKeyRequest represents a request to convert a mnemonic to a private key
type MnemonicToPrivateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mnemonic      string                 `protobuf:"bytes,1,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` // Derivation path, e.g., "m/44'/60'/0'/0/0"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MnemonicToPrivateKeyRequest) Reset() {
	*x = MnemonicToPrivateKeyRequest{}
	mi := &file_security_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MnemonicToPrivateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MnemonicToPrivateKeyRequest) ProtoMessage() {}

func (x *MnemonicToPrivateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MnemonicToPrivateKeyRequest.ProtoReflect.Descriptor instead.
func (*MnemonicToPrivateKeyRequest) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{14}
}

func (x *MnemonicToPrivateKeyRequest) GetMnemonic() string {
	if x != nil {
		return x.Mnemonic
	}
	return ""
}

func (x *MnemonicToPrivateKeyRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// MnemonicToPrivateKeyResponse represents a response to a convert mnemonic to private key request
type MnemonicToPrivateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey    string                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MnemonicToPrivateKeyResponse) Reset() {
	*x = MnemonicToPrivateKeyResponse{}
	mi := &file_security_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MnemonicToPrivateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MnemonicToPrivateKeyResponse) ProtoMessage() {}

func (x *MnemonicToPrivateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MnemonicToPrivateKeyResponse.ProtoReflect.Descriptor instead.
func (*MnemonicToPrivateKeyResponse) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{15}
}

func (x *MnemonicToPrivateKeyResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *MnemonicToPrivateKeyResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *MnemonicToPrivateKeyResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_security_proto protoreflect.FileDescriptor

const file_security_proto_rawDesc = "" +
	"\n" +
	"\x0esecurity.proto\x12\bsecurity\".\n" +
	"\x16GenerateKeyPairRequest\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\"s\n" +
	"\x17GenerateKeyPairResponse\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"[\n" +
	"\x18EncryptPrivateKeyRequest\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x02 \x01(\tR\n" +
	"passphrase\"@\n" +
	"\x19EncryptPrivateKeyResponse\x12#\n" +
	"\rencrypted_key\x18\x01 \x01(\tR\fencryptedKey\"_\n" +
	"\x18DecryptPrivateKeyRequest\x12#\n" +
	"\rencrypted_key\x18\x01 \x01(\tR\fencryptedKey\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x02 \x01(\tR\n" +
	"passphrase\"<\n" +
	"\x19DecryptPrivateKeyResponse\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\"w\n" +
	"\x12GenerateJWTRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1e\n" +
	"\n" +
	"expiration\x18\x04 \x01(\x03R\n" +
	"expiration\"o\n" +
	"\x13GenerateJWTResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"(\n" +
	"\x10VerifyJWTRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x8b\x01\n" +
	"\x11VerifyJWTResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\"5\n" +
	"\x17GenerateMnemonicRequest\x12\x1a\n" +
	"\bstrength\x18\x01 \x01(\x05R\bstrength\"6\n" +
	"\x18GenerateMnemonicResponse\x12\x1a\n" +
	"\bmnemonic\x18\x01 \x01(\tR\bmnemonic\"5\n" +
	"\x17ValidateMnemonicRequest\x12\x1a\n" +
	"\bmnemonic\x18\x01 \x01(\tR\bmnemonic\"0\n" +
	"\x18ValidateMnemonicResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\"M\n" +
	"\x1bMnemonicToPrivateKeyRequest\x12\x1a\n" +
	"\bmnemonic\x18\x01 \x01(\tR\bmnemonic\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"x\n" +
	"\x1cMnemonicToPrivateKeyResponse\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress2\xe4\x05\n" +
	"\x0fSecurityService\x12X\n" +
	"\x0fGenerateKeyPair\x12 .security.GenerateKeyPairRequest\x1a!.security.GenerateKeyPairResponse\"\x00\x12^\n" +
	"\x11EncryptPrivateKey\x12\".security.EncryptPrivateKeyRequest\x1a#.security.EncryptPrivateKeyResponse\"\x00\x12^\n" +
	"\x11DecryptPrivateKey\x12\".security.DecryptPrivateKeyRequest\x1a#.security.DecryptPrivateKeyResponse\"\x00\x12L\n" +
	"\vGenerateJWT\x12\x1c.security.GenerateJWTRequest\x1a\x1d.security.GenerateJWTResponse\"\x00\x12F\n" +
	"\tVerifyJWT\x12\x1a.security.VerifyJWTRequest\x1a\x1b.security.VerifyJWTResponse\"\x00\x12[\n" +
	"\x10GenerateMnemonic\x12!.security.GenerateMnemonicRequest\x1a\".security.GenerateMnemonicResponse\"\x00\x12[\n" +
	"\x10ValidateMnemonic\x12!.security.ValidateMnemonicRequest\x1a\".security.ValidateMnemonicResponse\"\x00\x12g\n" +
	"\x14MnemonicToPrivateKey\x12%.security.MnemonicToPrivateKeyRequest\x1a&.security.MnemonicToPrivateKeyResponse\"\x00BAZ?github.com/DimaJoyti/go-coffee/crypto-wallet/api/proto/securityb\x06proto3"

var (
	file_security_proto_rawDescOnce sync.Once
	file_security_proto_rawDescData []byte
)

func file_security_proto_rawDescGZIP() []byte {
	file_security_proto_rawDescOnce.Do(func() {
		file_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_security_proto_rawDesc), len(file_security_proto_rawDesc)))
	})
	return file_security_proto_rawDescData
}

var file_security_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_security_proto_goTypes = []any{
	(*GenerateKeyPairRequest)(nil),       // 0: security.GenerateKeyPairRequest
	(*GenerateKeyPairResponse)(nil),      // 1: security.GenerateKeyPairResponse
	(*EncryptPrivateKeyRequest)(nil),     // 2: security.EncryptPrivateKeyRequest
	(*EncryptPrivateKeyResponse)(nil),    // 3: security.EncryptPrivateKeyResponse
	(*DecryptPrivateKeyRequest)(nil),     // 4: security.DecryptPrivateKeyRequest
	(*DecryptPrivateKeyResponse)(nil),    // 5: security.DecryptPrivateKeyResponse
	(*GenerateJWTRequest)(nil),           // 6: security.GenerateJWTRequest
	(*GenerateJWTResponse)(nil),          // 7: security.GenerateJWTResponse
	(*VerifyJWTRequest)(nil),             // 8: security.VerifyJWTRequest
	(*VerifyJWTResponse)(nil),            // 9: security.VerifyJWTResponse
	(*GenerateMnemonicRequest)(nil),      // 10: security.GenerateMnemonicRequest
	(*GenerateMnemonicResponse)(nil),     // 11: security.GenerateMnemonicResponse
	(*ValidateMnemonicRequest)(nil),      // 12: security.ValidateMnemonicRequest
	(*ValidateMnemonicResponse)(nil),     // 13: security.ValidateMnemonicResponse
	(*MnemonicToPrivateKeyRequest)(nil),  // 14: security.MnemonicToPrivateKeyRequest
	(*MnemonicToPrivateKeyResponse)(nil), // 15: security.MnemonicToPrivateKeyResponse
}
var file_security_proto_depIdxs = []int32{
	0,  // 0: security.SecurityService.GenerateKeyPair:input_type -> security.GenerateKeyPairRequest
	2,  // 1: security.SecurityService.EncryptPrivateKey:input_type -> security.EncryptPrivateKeyRequest
	4,  // 2: security.SecurityService.DecryptPrivateKey:input_type -> security.DecryptPrivateKeyRequest
	6,  // 3: security.SecurityService.GenerateJWT:input_type -> security.GenerateJWTRequest
	8,  // 4: security.SecurityService.VerifyJWT:input_type -> security.VerifyJWTRequest
	10, // 5: security.SecurityService.GenerateMnemonic:input_type -> security.GenerateMnemonicRequest
	12, // 6: security.SecurityService.ValidateMnemonic:input_type -> security.ValidateMnemonicRequest
	14, // 7: security.SecurityService.MnemonicToPrivateKey:input_type -> security.MnemonicToPrivateKeyRequest
	1,  // 8: security.SecurityService.GenerateKeyPair:output_type -> security.GenerateKeyPairResponse
	3,  // 9: security.SecurityService.EncryptPrivateKey:output_type -> security.EncryptPrivateKeyResponse
	5,  // 10: security.SecurityService.DecryptPrivateKey:output_type -> security.DecryptPrivateKeyResponse
	7,  // 11: security.SecurityService.GenerateJWT:output_type -> security.GenerateJWTResponse
	9,  // 12: security.SecurityService.VerifyJWT:output_type -> security.VerifyJWTResponse
	11, // 13: security.SecurityService.GenerateMnemonic:output_type -> security.GenerateMnemonicResponse
	13, // 14: security.SecurityService.ValidateMnemonic:output_type -> security.ValidateMnemonicResponse
	15, // 15: security.SecurityService.MnemonicToPrivateKey:output_type -> security.MnemonicToPrivateKeyResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_security_proto_init() }
func file_security_proto_init() {
	if File_security_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_security_proto_rawDesc), len(file_security_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_security_proto_goTypes,
		DependencyIndexes: file_security_proto_depIdxs,
		MessageInfos:      file_security_proto_msgTypes,
	}.Build()
	File_security_proto = out.File
	file_security_proto_goTypes = nil
	file_security_proto_depIdxs = nil
}
