// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: ai_order.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Order status enumeration
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING     OrderStatus = 1
	OrderStatus_ORDER_STATUS_CONFIRMED   OrderStatus = 2
	OrderStatus_ORDER_STATUS_PREPARING   OrderStatus = 3
	OrderStatus_ORDER_STATUS_READY       OrderStatus = 4
	OrderStatus_ORDER_STATUS_COMPLETED   OrderStatus = 5
	OrderStatus_ORDER_STATUS_CANCELLED   OrderStatus = 6
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_CONFIRMED",
		3: "ORDER_STATUS_PREPARING",
		4: "ORDER_STATUS_READY",
		5: "ORDER_STATUS_COMPLETED",
		6: "ORDER_STATUS_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_PENDING":     1,
		"ORDER_STATUS_CONFIRMED":   2,
		"ORDER_STATUS_PREPARING":   3,
		"ORDER_STATUS_READY":       4,
		"ORDER_STATUS_COMPLETED":   5,
		"ORDER_STATUS_CANCELLED":   6,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_ai_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{0}
}

// Order priority based on AI analysis
type OrderPriority int32

const (
	OrderPriority_ORDER_PRIORITY_UNSPECIFIED OrderPriority = 0
	OrderPriority_ORDER_PRIORITY_LOW         OrderPriority = 1
	OrderPriority_ORDER_PRIORITY_NORMAL      OrderPriority = 2
	OrderPriority_ORDER_PRIORITY_HIGH        OrderPriority = 3
	OrderPriority_ORDER_PRIORITY_URGENT      OrderPriority = 4
)

// Enum value maps for OrderPriority.
var (
	OrderPriority_name = map[int32]string{
		0: "ORDER_PRIORITY_UNSPECIFIED",
		1: "ORDER_PRIORITY_LOW",
		2: "ORDER_PRIORITY_NORMAL",
		3: "ORDER_PRIORITY_HIGH",
		4: "ORDER_PRIORITY_URGENT",
	}
	OrderPriority_value = map[string]int32{
		"ORDER_PRIORITY_UNSPECIFIED": 0,
		"ORDER_PRIORITY_LOW":         1,
		"ORDER_PRIORITY_NORMAL":      2,
		"ORDER_PRIORITY_HIGH":        3,
		"ORDER_PRIORITY_URGENT":      4,
	}
)

func (x OrderPriority) Enum() *OrderPriority {
	p := new(OrderPriority)
	*p = x
	return p
}

func (x OrderPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_order_proto_enumTypes[1].Descriptor()
}

func (OrderPriority) Type() protoreflect.EnumType {
	return &file_ai_order_proto_enumTypes[1]
}

func (x OrderPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderPriority.Descriptor instead.
func (OrderPriority) EnumDescriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{1}
}

// Order item with AI enhancements
type OrderItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId      string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName    string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity       int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice      float64                `protobuf:"fixed64,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TotalPrice     float64                `protobuf:"fixed64,6,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Customizations []string               `protobuf:"bytes,7,rep,name=customizations,proto3" json:"customizations,omitempty"`
	AiInsights     *AIItemInsights        `protobuf:"bytes,8,opt,name=ai_insights,json=aiInsights,proto3" json:"ai_insights,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_ai_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *OrderItem) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderItem) GetCustomizations() []string {
	if x != nil {
		return x.Customizations
	}
	return nil
}

func (x *OrderItem) GetAiInsights() *AIItemInsights {
	if x != nil {
		return x.AiInsights
	}
	return nil
}

// AI insights for order items
type AIItemInsights struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	PopularityScore          float64                `protobuf:"fixed64,1,opt,name=popularity_score,json=popularityScore,proto3" json:"popularity_score,omitempty"`
	PreparationComplexity    float64                `protobuf:"fixed64,2,opt,name=preparation_complexity,json=preparationComplexity,proto3" json:"preparation_complexity,omitempty"`
	SuggestedPairings        []string               `protobuf:"bytes,3,rep,name=suggested_pairings,json=suggestedPairings,proto3" json:"suggested_pairings,omitempty"`
	EstimatedPrepTimeMinutes float64                `protobuf:"fixed64,4,opt,name=estimated_prep_time_minutes,json=estimatedPrepTimeMinutes,proto3" json:"estimated_prep_time_minutes,omitempty"`
	DietaryInfo              string                 `protobuf:"bytes,5,opt,name=dietary_info,json=dietaryInfo,proto3" json:"dietary_info,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AIItemInsights) Reset() {
	*x = AIItemInsights{}
	mi := &file_ai_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIItemInsights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIItemInsights) ProtoMessage() {}

func (x *AIItemInsights) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIItemInsights.ProtoReflect.Descriptor instead.
func (*AIItemInsights) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{1}
}

func (x *AIItemInsights) GetPopularityScore() float64 {
	if x != nil {
		return x.PopularityScore
	}
	return 0
}

func (x *AIItemInsights) GetPreparationComplexity() float64 {
	if x != nil {
		return x.PreparationComplexity
	}
	return 0
}

func (x *AIItemInsights) GetSuggestedPairings() []string {
	if x != nil {
		return x.SuggestedPairings
	}
	return nil
}

func (x *AIItemInsights) GetEstimatedPrepTimeMinutes() float64 {
	if x != nil {
		return x.EstimatedPrepTimeMinutes
	}
	return 0
}

func (x *AIItemInsights) GetDietaryInfo() string {
	if x != nil {
		return x.DietaryInfo
	}
	return ""
}

// Customer information with AI profile
type Customer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	AiProfile     *AICustomerProfile     `protobuf:"bytes,5,opt,name=ai_profile,json=aiProfile,proto3" json:"ai_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_ai_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{2}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Customer) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Customer) GetAiProfile() *AICustomerProfile {
	if x != nil {
		return x.AiProfile
	}
	return nil
}

// AI customer profile
type AICustomerProfile struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FavoriteItems      []string               `protobuf:"bytes,1,rep,name=favorite_items,json=favoriteItems,proto3" json:"favorite_items,omitempty"`
	LoyaltyScore       float64                `protobuf:"fixed64,2,opt,name=loyalty_score,json=loyaltyScore,proto3" json:"loyalty_score,omitempty"`
	PreferredTimeSlot  string                 `protobuf:"bytes,3,opt,name=preferred_time_slot,json=preferredTimeSlot,proto3" json:"preferred_time_slot,omitempty"`
	AverageOrderValue  float64                `protobuf:"fixed64,4,opt,name=average_order_value,json=averageOrderValue,proto3" json:"average_order_value,omitempty"`
	TotalOrders        int32                  `protobuf:"varint,5,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	DietaryPreferences []string               `protobuf:"bytes,6,rep,name=dietary_preferences,json=dietaryPreferences,proto3" json:"dietary_preferences,omitempty"`
	SatisfactionScore  float64                `protobuf:"fixed64,7,opt,name=satisfaction_score,json=satisfactionScore,proto3" json:"satisfaction_score,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AICustomerProfile) Reset() {
	*x = AICustomerProfile{}
	mi := &file_ai_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AICustomerProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AICustomerProfile) ProtoMessage() {}

func (x *AICustomerProfile) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AICustomerProfile.ProtoReflect.Descriptor instead.
func (*AICustomerProfile) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{3}
}

func (x *AICustomerProfile) GetFavoriteItems() []string {
	if x != nil {
		return x.FavoriteItems
	}
	return nil
}

func (x *AICustomerProfile) GetLoyaltyScore() float64 {
	if x != nil {
		return x.LoyaltyScore
	}
	return 0
}

func (x *AICustomerProfile) GetPreferredTimeSlot() string {
	if x != nil {
		return x.PreferredTimeSlot
	}
	return ""
}

func (x *AICustomerProfile) GetAverageOrderValue() float64 {
	if x != nil {
		return x.AverageOrderValue
	}
	return 0
}

func (x *AICustomerProfile) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *AICustomerProfile) GetDietaryPreferences() []string {
	if x != nil {
		return x.DietaryPreferences
	}
	return nil
}

func (x *AICustomerProfile) GetSatisfactionScore() float64 {
	if x != nil {
		return x.SatisfactionScore
	}
	return 0
}

// Order with AI enhancements
type Order struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Customer            *Customer              `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	Items               []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Status              OrderStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=ai_order.OrderStatus" json:"status,omitempty"`
	Priority            OrderPriority          `protobuf:"varint,5,opt,name=priority,proto3,enum=ai_order.OrderPriority" json:"priority,omitempty"`
	TotalAmount         float64                `protobuf:"fixed64,6,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	EstimatedCompletion *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=estimated_completion,json=estimatedCompletion,proto3" json:"estimated_completion,omitempty"`
	LocationId          string                 `protobuf:"bytes,10,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	AiInsights          *AIOrderInsights       `protobuf:"bytes,11,opt,name=ai_insights,json=aiInsights,proto3" json:"ai_insights,omitempty"`
	SpecialInstructions string                 `protobuf:"bytes,12,opt,name=special_instructions,json=specialInstructions,proto3" json:"special_instructions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_ai_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{4}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetPriority() OrderPriority {
	if x != nil {
		return x.Priority
	}
	return OrderPriority_ORDER_PRIORITY_UNSPECIFIED
}

func (x *Order) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Order) GetEstimatedCompletion() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedCompletion
	}
	return nil
}

func (x *Order) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *Order) GetAiInsights() *AIOrderInsights {
	if x != nil {
		return x.AiInsights
	}
	return nil
}

func (x *Order) GetSpecialInstructions() string {
	if x != nil {
		return x.SpecialInstructions
	}
	return ""
}

// AI insights for orders
type AIOrderInsights struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	ComplexityScore                float64                `protobuf:"fixed64,1,opt,name=complexity_score,json=complexityScore,proto3" json:"complexity_score,omitempty"`
	EstimatedPrepTimeMinutes       float64                `protobuf:"fixed64,2,opt,name=estimated_prep_time_minutes,json=estimatedPrepTimeMinutes,proto3" json:"estimated_prep_time_minutes,omitempty"`
	RecommendedAdditions           []string               `protobuf:"bytes,3,rep,name=recommended_additions,json=recommendedAdditions,proto3" json:"recommended_additions,omitempty"`
	RevenueImpact                  float64                `protobuf:"fixed64,4,opt,name=revenue_impact,json=revenueImpact,proto3" json:"revenue_impact,omitempty"`
	PeakTimeAnalysis               string                 `protobuf:"bytes,5,opt,name=peak_time_analysis,json=peakTimeAnalysis,proto3" json:"peak_time_analysis,omitempty"`
	CustomerSatisfactionPrediction float64                `protobuf:"fixed64,6,opt,name=customer_satisfaction_prediction,json=customerSatisfactionPrediction,proto3" json:"customer_satisfaction_prediction,omitempty"`
	OptimizationSuggestions        []string               `protobuf:"bytes,7,rep,name=optimization_suggestions,json=optimizationSuggestions,proto3" json:"optimization_suggestions,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *AIOrderInsights) Reset() {
	*x = AIOrderInsights{}
	mi := &file_ai_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIOrderInsights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIOrderInsights) ProtoMessage() {}

func (x *AIOrderInsights) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIOrderInsights.ProtoReflect.Descriptor instead.
func (*AIOrderInsights) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{5}
}

func (x *AIOrderInsights) GetComplexityScore() float64 {
	if x != nil {
		return x.ComplexityScore
	}
	return 0
}

func (x *AIOrderInsights) GetEstimatedPrepTimeMinutes() float64 {
	if x != nil {
		return x.EstimatedPrepTimeMinutes
	}
	return 0
}

func (x *AIOrderInsights) GetRecommendedAdditions() []string {
	if x != nil {
		return x.RecommendedAdditions
	}
	return nil
}

func (x *AIOrderInsights) GetRevenueImpact() float64 {
	if x != nil {
		return x.RevenueImpact
	}
	return 0
}

func (x *AIOrderInsights) GetPeakTimeAnalysis() string {
	if x != nil {
		return x.PeakTimeAnalysis
	}
	return ""
}

func (x *AIOrderInsights) GetCustomerSatisfactionPrediction() float64 {
	if x != nil {
		return x.CustomerSatisfactionPrediction
	}
	return 0
}

func (x *AIOrderInsights) GetOptimizationSuggestions() []string {
	if x != nil {
		return x.OptimizationSuggestions
	}
	return nil
}

// Create Order Request
type CreateOrderRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Customer             *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	Items                []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	LocationId           string                 `protobuf:"bytes,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	SpecialInstructions  string                 `protobuf:"bytes,4,opt,name=special_instructions,json=specialInstructions,proto3" json:"special_instructions,omitempty"`
	EnableAiOptimization bool                   `protobuf:"varint,5,opt,name=enable_ai_optimization,json=enableAiOptimization,proto3" json:"enable_ai_optimization,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_ai_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{6}
}

func (x *CreateOrderRequest) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *CreateOrderRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateOrderRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *CreateOrderRequest) GetSpecialInstructions() string {
	if x != nil {
		return x.SpecialInstructions
	}
	return ""
}

func (x *CreateOrderRequest) GetEnableAiOptimization() bool {
	if x != nil {
		return x.EnableAiOptimization
	}
	return false
}

// Create Order Response
type CreateOrderResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Order                    *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	AiRecommendations        []string               `protobuf:"bytes,2,rep,name=ai_recommendations,json=aiRecommendations,proto3" json:"ai_recommendations,omitempty"`
	EstimatedWaitTimeMinutes float64                `protobuf:"fixed64,3,opt,name=estimated_wait_time_minutes,json=estimatedWaitTimeMinutes,proto3" json:"estimated_wait_time_minutes,omitempty"`
	Success                  bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Message                  string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_ai_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{7}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CreateOrderResponse) GetAiRecommendations() []string {
	if x != nil {
		return x.AiRecommendations
	}
	return nil
}

func (x *CreateOrderResponse) GetEstimatedWaitTimeMinutes() float64 {
	if x != nil {
		return x.EstimatedWaitTimeMinutes
	}
	return 0
}

func (x *CreateOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Get Order Request
type GetOrderRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderId           string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	IncludeAiInsights bool                   `protobuf:"varint,2,opt,name=include_ai_insights,json=includeAiInsights,proto3" json:"include_ai_insights,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_ai_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderRequest) GetIncludeAiInsights() bool {
	if x != nil {
		return x.IncludeAiInsights
	}
	return false
}

// Get Order Response
type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_ai_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *GetOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// List Orders Request
type ListOrdersRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CustomerId        string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	LocationId        string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Status            OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=ai_order.OrderStatus" json:"status,omitempty"`
	FromDate          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	PageSize          int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken         string                 `protobuf:"bytes,7,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	EnableAiFiltering bool                   `protobuf:"varint,8,opt,name=enable_ai_filtering,json=enableAiFiltering,proto3" json:"enable_ai_filtering,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_ai_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{10}
}

func (x *ListOrdersRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListOrdersRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *ListOrdersRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *ListOrdersRequest) GetFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FromDate
	}
	return nil
}

func (x *ListOrdersRequest) GetToDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ToDate
	}
	return nil
}

func (x *ListOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrdersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListOrdersRequest) GetEnableAiFiltering() bool {
	if x != nil {
		return x.EnableAiFiltering
	}
	return false
}

// List Orders Response
type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	AiAnalytics   *AIAnalytics           `protobuf:"bytes,4,opt,name=ai_analytics,json=aiAnalytics,proto3" json:"ai_analytics,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_ai_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{11}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListOrdersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListOrdersResponse) GetAiAnalytics() *AIAnalytics {
	if x != nil {
		return x.AiAnalytics
	}
	return nil
}

func (x *ListOrdersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListOrdersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// AI Analytics for order lists
type AIAnalytics struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	AverageOrderValue       float64                `protobuf:"fixed64,1,opt,name=average_order_value,json=averageOrderValue,proto3" json:"average_order_value,omitempty"`
	TotalRevenue            float64                `protobuf:"fixed64,2,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	PopularItems            []string               `protobuf:"bytes,3,rep,name=popular_items,json=popularItems,proto3" json:"popular_items,omitempty"`
	CustomerSatisfactionAvg float64                `protobuf:"fixed64,4,opt,name=customer_satisfaction_avg,json=customerSatisfactionAvg,proto3" json:"customer_satisfaction_avg,omitempty"`
	PeakHourAnalysis        float64                `protobuf:"fixed64,5,opt,name=peak_hour_analysis,json=peakHourAnalysis,proto3" json:"peak_hour_analysis,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AIAnalytics) Reset() {
	*x = AIAnalytics{}
	mi := &file_ai_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIAnalytics) ProtoMessage() {}

func (x *AIAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIAnalytics.ProtoReflect.Descriptor instead.
func (*AIAnalytics) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{12}
}

func (x *AIAnalytics) GetAverageOrderValue() float64 {
	if x != nil {
		return x.AverageOrderValue
	}
	return 0
}

func (x *AIAnalytics) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *AIAnalytics) GetPopularItems() []string {
	if x != nil {
		return x.PopularItems
	}
	return nil
}

func (x *AIAnalytics) GetCustomerSatisfactionAvg() float64 {
	if x != nil {
		return x.CustomerSatisfactionAvg
	}
	return 0
}

func (x *AIAnalytics) GetPeakHourAnalysis() float64 {
	if x != nil {
		return x.PeakHourAnalysis
	}
	return 0
}

// Update Order Status Request
type UpdateOrderStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	NewStatus      OrderStatus            `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=ai_order.OrderStatus" json:"new_status,omitempty"`
	Reason         string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	NotifyCustomer bool                   `protobuf:"varint,4,opt,name=notify_customer,json=notifyCustomer,proto3" json:"notify_customer,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_ai_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetNewStatus() OrderStatus {
	if x != nil {
		return x.NewStatus
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *UpdateOrderStatusRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetNotifyCustomer() bool {
	if x != nil {
		return x.NotifyCustomer
	}
	return false
}

// Update Order Status Response
type UpdateOrderStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Order           *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	AiNotifications []string               `protobuf:"bytes,2,rep,name=ai_notifications,json=aiNotifications,proto3" json:"ai_notifications,omitempty"`
	Success         bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateOrderStatusResponse) Reset() {
	*x = UpdateOrderStatusResponse{}
	mi := &file_ai_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusResponse) ProtoMessage() {}

func (x *UpdateOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateOrderStatusResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *UpdateOrderStatusResponse) GetAiNotifications() []string {
	if x != nil {
		return x.AiNotifications
	}
	return nil
}

func (x *UpdateOrderStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateOrderStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Cancel Order Request
type CancelOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RefundRequired bool                   `protobuf:"varint,3,opt,name=refund_required,json=refundRequired,proto3" json:"refund_required,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_ai_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{15}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelOrderRequest) GetRefundRequired() bool {
	if x != nil {
		return x.RefundRequired
	}
	return false
}

// Cancel Order Response
type CancelOrderResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Order          *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	ImpactAnalysis *AIImpactAnalysis      `protobuf:"bytes,2,opt,name=impact_analysis,json=impactAnalysis,proto3" json:"impact_analysis,omitempty"`
	Success        bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_ai_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{16}
}

func (x *CancelOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CancelOrderResponse) GetImpactAnalysis() *AIImpactAnalysis {
	if x != nil {
		return x.ImpactAnalysis
	}
	return nil
}

func (x *CancelOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// AI Impact Analysis for cancellations
type AIImpactAnalysis struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	RevenueImpact              float64                `protobuf:"fixed64,1,opt,name=revenue_impact,json=revenueImpact,proto3" json:"revenue_impact,omitempty"`
	CustomerSatisfactionImpact float64                `protobuf:"fixed64,2,opt,name=customer_satisfaction_impact,json=customerSatisfactionImpact,proto3" json:"customer_satisfaction_impact,omitempty"`
	MitigationSuggestions      []string               `protobuf:"bytes,3,rep,name=mitigation_suggestions,json=mitigationSuggestions,proto3" json:"mitigation_suggestions,omitempty"`
	KitchenEfficiencyImpact    float64                `protobuf:"fixed64,4,opt,name=kitchen_efficiency_impact,json=kitchenEfficiencyImpact,proto3" json:"kitchen_efficiency_impact,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *AIImpactAnalysis) Reset() {
	*x = AIImpactAnalysis{}
	mi := &file_ai_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIImpactAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIImpactAnalysis) ProtoMessage() {}

func (x *AIImpactAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIImpactAnalysis.ProtoReflect.Descriptor instead.
func (*AIImpactAnalysis) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{17}
}

func (x *AIImpactAnalysis) GetRevenueImpact() float64 {
	if x != nil {
		return x.RevenueImpact
	}
	return 0
}

func (x *AIImpactAnalysis) GetCustomerSatisfactionImpact() float64 {
	if x != nil {
		return x.CustomerSatisfactionImpact
	}
	return 0
}

func (x *AIImpactAnalysis) GetMitigationSuggestions() []string {
	if x != nil {
		return x.MitigationSuggestions
	}
	return nil
}

func (x *AIImpactAnalysis) GetKitchenEfficiencyImpact() float64 {
	if x != nil {
		return x.KitchenEfficiencyImpact
	}
	return 0
}

// Get Order Recommendations Request
type GetOrderRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	CurrentItems  []string               `protobuf:"bytes,3,rep,name=current_items,json=currentItems,proto3" json:"current_items,omitempty"`
	TimeOfDay     string                 `protobuf:"bytes,4,opt,name=time_of_day,json=timeOfDay,proto3" json:"time_of_day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRecommendationsRequest) Reset() {
	*x = GetOrderRecommendationsRequest{}
	mi := &file_ai_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRecommendationsRequest) ProtoMessage() {}

func (x *GetOrderRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{18}
}

func (x *GetOrderRecommendationsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GetOrderRecommendationsRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *GetOrderRecommendationsRequest) GetCurrentItems() []string {
	if x != nil {
		return x.CurrentItems
	}
	return nil
}

func (x *GetOrderRecommendationsRequest) GetTimeOfDay() string {
	if x != nil {
		return x.TimeOfDay
	}
	return ""
}

// Get Order Recommendations Response
type GetOrderRecommendationsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*RecommendedItem     `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	Reasoning       string                 `protobuf:"bytes,2,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	Success         bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetOrderRecommendationsResponse) Reset() {
	*x = GetOrderRecommendationsResponse{}
	mi := &file_ai_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRecommendationsResponse) ProtoMessage() {}

func (x *GetOrderRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetOrderRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{19}
}

func (x *GetOrderRecommendationsResponse) GetRecommendations() []*RecommendedItem {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *GetOrderRecommendationsResponse) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *GetOrderRecommendationsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetOrderRecommendationsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Recommended item with AI scoring
type RecommendedItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductId         string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName       string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ConfidenceScore   float64                `protobuf:"fixed64,3,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Reason            string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Price             float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	EstimatedPrepTime float64                `protobuf:"fixed64,6,opt,name=estimated_prep_time,json=estimatedPrepTime,proto3" json:"estimated_prep_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecommendedItem) Reset() {
	*x = RecommendedItem{}
	mi := &file_ai_order_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedItem) ProtoMessage() {}

func (x *RecommendedItem) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedItem.ProtoReflect.Descriptor instead.
func (*RecommendedItem) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{20}
}

func (x *RecommendedItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *RecommendedItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *RecommendedItem) GetConfidenceScore() float64 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *RecommendedItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RecommendedItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *RecommendedItem) GetEstimatedPrepTime() float64 {
	if x != nil {
		return x.EstimatedPrepTime
	}
	return 0
}

// Analyze Order Patterns Request
type AnalyzeOrderPatternsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    string                 `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	FromDate      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	AnalysisType  string                 `protobuf:"bytes,4,opt,name=analysis_type,json=analysisType,proto3" json:"analysis_type,omitempty"` // "daily", "weekly", "monthly"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeOrderPatternsRequest) Reset() {
	*x = AnalyzeOrderPatternsRequest{}
	mi := &file_ai_order_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeOrderPatternsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeOrderPatternsRequest) ProtoMessage() {}

func (x *AnalyzeOrderPatternsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeOrderPatternsRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeOrderPatternsRequest) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{21}
}

func (x *AnalyzeOrderPatternsRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *AnalyzeOrderPatternsRequest) GetFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FromDate
	}
	return nil
}

func (x *AnalyzeOrderPatternsRequest) GetToDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ToDate
	}
	return nil
}

func (x *AnalyzeOrderPatternsRequest) GetAnalysisType() string {
	if x != nil {
		return x.AnalysisType
	}
	return ""
}

// Analyze Order Patterns Response
type AnalyzeOrderPatternsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Insights        []*PatternInsight      `protobuf:"bytes,1,rep,name=insights,proto3" json:"insights,omitempty"`
	Recommendations []string               `protobuf:"bytes,2,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	Success         bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeOrderPatternsResponse) Reset() {
	*x = AnalyzeOrderPatternsResponse{}
	mi := &file_ai_order_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeOrderPatternsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeOrderPatternsResponse) ProtoMessage() {}

func (x *AnalyzeOrderPatternsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeOrderPatternsResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeOrderPatternsResponse) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{22}
}

func (x *AnalyzeOrderPatternsResponse) GetInsights() []*PatternInsight {
	if x != nil {
		return x.Insights
	}
	return nil
}

func (x *AnalyzeOrderPatternsResponse) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *AnalyzeOrderPatternsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AnalyzeOrderPatternsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Pattern insight from AI analysis
type PatternInsight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatternType   string                 `protobuf:"bytes,1,opt,name=pattern_type,json=patternType,proto3" json:"pattern_type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	AffectedItems []string               `protobuf:"bytes,4,rep,name=affected_items,json=affectedItems,proto3" json:"affected_items,omitempty"`
	TimePeriod    string                 `protobuf:"bytes,5,opt,name=time_period,json=timePeriod,proto3" json:"time_period,omitempty"`
	ImpactScore   float64                `protobuf:"fixed64,6,opt,name=impact_score,json=impactScore,proto3" json:"impact_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatternInsight) Reset() {
	*x = PatternInsight{}
	mi := &file_ai_order_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatternInsight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatternInsight) ProtoMessage() {}

func (x *PatternInsight) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatternInsight.ProtoReflect.Descriptor instead.
func (*PatternInsight) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{23}
}

func (x *PatternInsight) GetPatternType() string {
	if x != nil {
		return x.PatternType
	}
	return ""
}

func (x *PatternInsight) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PatternInsight) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PatternInsight) GetAffectedItems() []string {
	if x != nil {
		return x.AffectedItems
	}
	return nil
}

func (x *PatternInsight) GetTimePeriod() string {
	if x != nil {
		return x.TimePeriod
	}
	return ""
}

func (x *PatternInsight) GetImpactScore() float64 {
	if x != nil {
		return x.ImpactScore
	}
	return 0
}

// Predict Completion Time Request
type PredictCompletionTimeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderId          string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	LocationId       string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	CurrentQueueSize int32                  `protobuf:"varint,3,opt,name=current_queue_size,json=currentQueueSize,proto3" json:"current_queue_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PredictCompletionTimeRequest) Reset() {
	*x = PredictCompletionTimeRequest{}
	mi := &file_ai_order_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictCompletionTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictCompletionTimeRequest) ProtoMessage() {}

func (x *PredictCompletionTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictCompletionTimeRequest.ProtoReflect.Descriptor instead.
func (*PredictCompletionTimeRequest) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{24}
}

func (x *PredictCompletionTimeRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PredictCompletionTimeRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *PredictCompletionTimeRequest) GetCurrentQueueSize() int32 {
	if x != nil {
		return x.CurrentQueueSize
	}
	return 0
}

// Predict Completion Time Response
type PredictCompletionTimeResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	EstimatedMinutes        float64                `protobuf:"fixed64,1,opt,name=estimated_minutes,json=estimatedMinutes,proto3" json:"estimated_minutes,omitempty"`
	ConfidenceLevel         float64                `protobuf:"fixed64,2,opt,name=confidence_level,json=confidenceLevel,proto3" json:"confidence_level,omitempty"`
	Factors                 []string               `protobuf:"bytes,3,rep,name=factors,proto3" json:"factors,omitempty"`
	EstimatedCompletionTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=estimated_completion_time,json=estimatedCompletionTime,proto3" json:"estimated_completion_time,omitempty"`
	Success                 bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Message                 string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PredictCompletionTimeResponse) Reset() {
	*x = PredictCompletionTimeResponse{}
	mi := &file_ai_order_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictCompletionTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictCompletionTimeResponse) ProtoMessage() {}

func (x *PredictCompletionTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_order_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictCompletionTimeResponse.ProtoReflect.Descriptor instead.
func (*PredictCompletionTimeResponse) Descriptor() ([]byte, []int) {
	return file_ai_order_proto_rawDescGZIP(), []int{25}
}

func (x *PredictCompletionTimeResponse) GetEstimatedMinutes() float64 {
	if x != nil {
		return x.EstimatedMinutes
	}
	return 0
}

func (x *PredictCompletionTimeResponse) GetConfidenceLevel() float64 {
	if x != nil {
		return x.ConfidenceLevel
	}
	return 0
}

func (x *PredictCompletionTimeResponse) GetFactors() []string {
	if x != nil {
		return x.Factors
	}
	return nil
}

func (x *PredictCompletionTimeResponse) GetEstimatedCompletionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedCompletionTime
	}
	return nil
}

func (x *PredictCompletionTimeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PredictCompletionTimeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ai_order_proto protoreflect.FileDescriptor

const file_ai_order_proto_rawDesc = "" +
	"\n" +
	"\x0eai_order.proto\x12\bai_order\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x02\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x05 \x01(\x01R\tunitPrice\x12\x1f\n" +
	"\vtotal_price\x18\x06 \x01(\x01R\n" +
	"totalPrice\x12&\n" +
	"\x0ecustomizations\x18\a \x03(\tR\x0ecustomizations\x129\n" +
	"\vai_insights\x18\b \x01(\v2\x18.ai_order.AIItemInsightsR\n" +
	"aiInsights\"\x83\x02\n" +
	"\x0eAIItemInsights\x12)\n" +
	"\x10popularity_score\x18\x01 \x01(\x01R\x0fpopularityScore\x125\n" +
	"\x16preparation_complexity\x18\x02 \x01(\x01R\x15preparationComplexity\x12-\n" +
	"\x12suggested_pairings\x18\x03 \x03(\tR\x11suggestedPairings\x12=\n" +
	"\x1bestimated_prep_time_minutes\x18\x04 \x01(\x01R\x18estimatedPrepTimeMinutes\x12!\n" +
	"\fdietary_info\x18\x05 \x01(\tR\vdietaryInfo\"\x96\x01\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12:\n" +
	"\n" +
	"ai_profile\x18\x05 \x01(\v2\x1b.ai_order.AICustomerProfileR\taiProfile\"\xc2\x02\n" +
	"\x11AICustomerProfile\x12%\n" +
	"\x0efavorite_items\x18\x01 \x03(\tR\rfavoriteItems\x12#\n" +
	"\rloyalty_score\x18\x02 \x01(\x01R\floyaltyScore\x12.\n" +
	"\x13preferred_time_slot\x18\x03 \x01(\tR\x11preferredTimeSlot\x12.\n" +
	"\x13average_order_value\x18\x04 \x01(\x01R\x11averageOrderValue\x12!\n" +
	"\ftotal_orders\x18\x05 \x01(\x05R\vtotalOrders\x12/\n" +
	"\x13dietary_preferences\x18\x06 \x03(\tR\x12dietaryPreferences\x12-\n" +
	"\x12satisfaction_score\x18\a \x01(\x01R\x11satisfactionScore\"\xce\x04\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\bcustomer\x18\x02 \x01(\v2\x12.ai_order.CustomerR\bcustomer\x12)\n" +
	"\x05items\x18\x03 \x03(\v2\x13.ai_order.OrderItemR\x05items\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.ai_order.OrderStatusR\x06status\x123\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x17.ai_order.OrderPriorityR\bpriority\x12!\n" +
	"\ftotal_amount\x18\x06 \x01(\x01R\vtotalAmount\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12M\n" +
	"\x14estimated_completion\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x13estimatedCompletion\x12\x1f\n" +
	"\vlocation_id\x18\n" +
	" \x01(\tR\n" +
	"locationId\x12:\n" +
	"\vai_insights\x18\v \x01(\v2\x19.ai_order.AIOrderInsightsR\n" +
	"aiInsights\x121\n" +
	"\x14special_instructions\x18\f \x01(\tR\x13specialInstructions\"\x8a\x03\n" +
	"\x0fAIOrderInsights\x12)\n" +
	"\x10complexity_score\x18\x01 \x01(\x01R\x0fcomplexityScore\x12=\n" +
	"\x1bestimated_prep_time_minutes\x18\x02 \x01(\x01R\x18estimatedPrepTimeMinutes\x123\n" +
	"\x15recommended_additions\x18\x03 \x03(\tR\x14recommendedAdditions\x12%\n" +
	"\x0erevenue_impact\x18\x04 \x01(\x01R\rrevenueImpact\x12,\n" +
	"\x12peak_time_analysis\x18\x05 \x01(\tR\x10peakTimeAnalysis\x12H\n" +
	" customer_satisfaction_prediction\x18\x06 \x01(\x01R\x1ecustomerSatisfactionPrediction\x129\n" +
	"\x18optimization_suggestions\x18\a \x03(\tR\x17optimizationSuggestions\"\xf9\x01\n" +
	"\x12CreateOrderRequest\x12.\n" +
	"\bcustomer\x18\x01 \x01(\v2\x12.ai_order.CustomerR\bcustomer\x12)\n" +
	"\x05items\x18\x02 \x03(\v2\x13.ai_order.OrderItemR\x05items\x12\x1f\n" +
	"\vlocation_id\x18\x03 \x01(\tR\n" +
	"locationId\x121\n" +
	"\x14special_instructions\x18\x04 \x01(\tR\x13specialInstructions\x124\n" +
	"\x16enable_ai_optimization\x18\x05 \x01(\bR\x14enableAiOptimization\"\xde\x01\n" +
	"\x13CreateOrderResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.ai_order.OrderR\x05order\x12-\n" +
	"\x12ai_recommendations\x18\x02 \x03(\tR\x11aiRecommendations\x12=\n" +
	"\x1bestimated_wait_time_minutes\x18\x03 \x01(\x01R\x18estimatedWaitTimeMinutes\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\\\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12.\n" +
	"\x13include_ai_insights\x18\x02 \x01(\bR\x11includeAiInsights\"m\n" +
	"\x10GetOrderResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.ai_order.OrderR\x05order\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xde\x02\n" +
	"\x11ListOrdersRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.ai_order.OrderStatusR\x06status\x127\n" +
	"\tfrom_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bfromDate\x123\n" +
	"\ato_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06toDate\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\a \x01(\tR\tpageToken\x12.\n" +
	"\x13enable_ai_filtering\x18\b \x01(\bR\x11enableAiFiltering\"\xf4\x01\n" +
	"\x12ListOrdersResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.ai_order.OrderR\x06orders\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x128\n" +
	"\fai_analytics\x18\x04 \x01(\v2\x15.ai_order.AIAnalyticsR\vaiAnalytics\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\xf1\x01\n" +
	"\vAIAnalytics\x12.\n" +
	"\x13average_order_value\x18\x01 \x01(\x01R\x11averageOrderValue\x12#\n" +
	"\rtotal_revenue\x18\x02 \x01(\x01R\ftotalRevenue\x12#\n" +
	"\rpopular_items\x18\x03 \x03(\tR\fpopularItems\x12:\n" +
	"\x19customer_satisfaction_avg\x18\x04 \x01(\x01R\x17customerSatisfactionAvg\x12,\n" +
	"\x12peak_hour_analysis\x18\x05 \x01(\x01R\x10peakHourAnalysis\"\xac\x01\n" +
	"\x18UpdateOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x124\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x15.ai_order.OrderStatusR\tnewStatus\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12'\n" +
	"\x0fnotify_customer\x18\x04 \x01(\bR\x0enotifyCustomer\"\xa1\x01\n" +
	"\x19UpdateOrderStatusResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.ai_order.OrderR\x05order\x12)\n" +
	"\x10ai_notifications\x18\x02 \x03(\tR\x0faiNotifications\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"p\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12'\n" +
	"\x0frefund_required\x18\x03 \x01(\bR\x0erefundRequired\"\xb5\x01\n" +
	"\x13CancelOrderResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.ai_order.OrderR\x05order\x12C\n" +
	"\x0fimpact_analysis\x18\x02 \x01(\v2\x1a.ai_order.AIImpactAnalysisR\x0eimpactAnalysis\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xee\x01\n" +
	"\x10AIImpactAnalysis\x12%\n" +
	"\x0erevenue_impact\x18\x01 \x01(\x01R\rrevenueImpact\x12@\n" +
	"\x1ccustomer_satisfaction_impact\x18\x02 \x01(\x01R\x1acustomerSatisfactionImpact\x125\n" +
	"\x16mitigation_suggestions\x18\x03 \x03(\tR\x15mitigationSuggestions\x12:\n" +
	"\x19kitchen_efficiency_impact\x18\x04 \x01(\x01R\x17kitchenEfficiencyImpact\"\xa7\x01\n" +
	"\x1eGetOrderRecommendationsRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12#\n" +
	"\rcurrent_items\x18\x03 \x03(\tR\fcurrentItems\x12\x1e\n" +
	"\vtime_of_day\x18\x04 \x01(\tR\ttimeOfDay\"\xb8\x01\n" +
	"\x1fGetOrderRecommendationsResponse\x12C\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x19.ai_order.RecommendedItemR\x0frecommendations\x12\x1c\n" +
	"\treasoning\x18\x02 \x01(\tR\treasoning\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xdc\x01\n" +
	"\x0fRecommendedItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12)\n" +
	"\x10confidence_score\x18\x03 \x01(\x01R\x0fconfidenceScore\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12.\n" +
	"\x13estimated_prep_time\x18\x06 \x01(\x01R\x11estimatedPrepTime\"\xd1\x01\n" +
	"\x1bAnalyzeOrderPatternsRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\x127\n" +
	"\tfrom_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bfromDate\x123\n" +
	"\ato_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06toDate\x12#\n" +
	"\ranalysis_type\x18\x04 \x01(\tR\fanalysisType\"\xb2\x01\n" +
	"\x1cAnalyzeOrderPatternsResponse\x124\n" +
	"\binsights\x18\x01 \x03(\v2\x18.ai_order.PatternInsightR\binsights\x12(\n" +
	"\x0frecommendations\x18\x02 \x03(\tR\x0frecommendations\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xe0\x01\n" +
	"\x0ePatternInsight\x12!\n" +
	"\fpattern_type\x18\x01 \x01(\tR\vpatternType\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12%\n" +
	"\x0eaffected_items\x18\x04 \x03(\tR\raffectedItems\x12\x1f\n" +
	"\vtime_period\x18\x05 \x01(\tR\n" +
	"timePeriod\x12!\n" +
	"\fimpact_score\x18\x06 \x01(\x01R\vimpactScore\"\x88\x01\n" +
	"\x1cPredictCompletionTimeRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12,\n" +
	"\x12current_queue_size\x18\x03 \x01(\x05R\x10currentQueueSize\"\x9d\x02\n" +
	"\x1dPredictCompletionTimeResponse\x12+\n" +
	"\x11estimated_minutes\x18\x01 \x01(\x01R\x10estimatedMinutes\x12)\n" +
	"\x10confidence_level\x18\x02 \x01(\x01R\x0fconfidenceLevel\x12\x18\n" +
	"\afactors\x18\x03 \x03(\tR\afactors\x12V\n" +
	"\x19estimated_completion_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x17estimatedCompletionTime\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage*\xcd\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16ORDER_STATUS_CONFIRMED\x10\x02\x12\x1a\n" +
	"\x16ORDER_STATUS_PREPARING\x10\x03\x12\x16\n" +
	"\x12ORDER_STATUS_READY\x10\x04\x12\x1a\n" +
	"\x16ORDER_STATUS_COMPLETED\x10\x05\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x06*\x96\x01\n" +
	"\rOrderPriority\x12\x1e\n" +
	"\x1aORDER_PRIORITY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ORDER_PRIORITY_LOW\x10\x01\x12\x19\n" +
	"\x15ORDER_PRIORITY_NORMAL\x10\x02\x12\x17\n" +
	"\x13ORDER_PRIORITY_HIGH\x10\x03\x12\x19\n" +
	"\x15ORDER_PRIORITY_URGENT\x10\x042\xd3\x05\n" +
	"\x0eAIOrderService\x12J\n" +
	"\vCreateOrder\x12\x1c.ai_order.CreateOrderRequest\x1a\x1d.ai_order.CreateOrderResponse\x12A\n" +
	"\bGetOrder\x12\x19.ai_order.GetOrderRequest\x1a\x1a.ai_order.GetOrderResponse\x12G\n" +
	"\n" +
	"ListOrders\x12\x1b.ai_order.ListOrdersRequest\x1a\x1c.ai_order.ListOrdersResponse\x12\\\n" +
	"\x11UpdateOrderStatus\x12\".ai_order.UpdateOrderStatusRequest\x1a#.ai_order.UpdateOrderStatusResponse\x12J\n" +
	"\vCancelOrder\x12\x1c.ai_order.CancelOrderRequest\x1a\x1d.ai_order.CancelOrderResponse\x12n\n" +
	"\x17GetOrderRecommendations\x12(.ai_order.GetOrderRecommendationsRequest\x1a).ai_order.GetOrderRecommendationsResponse\x12e\n" +
	"\x14AnalyzeOrderPatterns\x12%.ai_order.AnalyzeOrderPatternsRequest\x1a&.ai_order.AnalyzeOrderPatternsResponse\x12h\n" +
	"\x15PredictCompletionTime\x12&.ai_order.PredictCompletionTimeRequest\x1a'.ai_order.PredictCompletionTimeResponseB3Z1github.com/DimaJoyti/go-coffee/api/proto/ai_orderb\x06proto3"

var (
	file_ai_order_proto_rawDescOnce sync.Once
	file_ai_order_proto_rawDescData []byte
)

func file_ai_order_proto_rawDescGZIP() []byte {
	file_ai_order_proto_rawDescOnce.Do(func() {
		file_ai_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_order_proto_rawDesc), len(file_ai_order_proto_rawDesc)))
	})
	return file_ai_order_proto_rawDescData
}

var file_ai_order_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ai_order_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_ai_order_proto_goTypes = []any{
	(OrderStatus)(0),                        // 0: ai_order.OrderStatus
	(OrderPriority)(0),                      // 1: ai_order.OrderPriority
	(*OrderItem)(nil),                       // 2: ai_order.OrderItem
	(*AIItemInsights)(nil),                  // 3: ai_order.AIItemInsights
	(*Customer)(nil),                        // 4: ai_order.Customer
	(*AICustomerProfile)(nil),               // 5: ai_order.AICustomerProfile
	(*Order)(nil),                           // 6: ai_order.Order
	(*AIOrderInsights)(nil),                 // 7: ai_order.AIOrderInsights
	(*CreateOrderRequest)(nil),              // 8: ai_order.CreateOrderRequest
	(*CreateOrderResponse)(nil),             // 9: ai_order.CreateOrderResponse
	(*GetOrderRequest)(nil),                 // 10: ai_order.GetOrderRequest
	(*GetOrderResponse)(nil),                // 11: ai_order.GetOrderResponse
	(*ListOrdersRequest)(nil),               // 12: ai_order.ListOrdersRequest
	(*ListOrdersResponse)(nil),              // 13: ai_order.ListOrdersResponse
	(*AIAnalytics)(nil),                     // 14: ai_order.AIAnalytics
	(*UpdateOrderStatusRequest)(nil),        // 15: ai_order.UpdateOrderStatusRequest
	(*UpdateOrderStatusResponse)(nil),       // 16: ai_order.UpdateOrderStatusResponse
	(*CancelOrderRequest)(nil),              // 17: ai_order.CancelOrderRequest
	(*CancelOrderResponse)(nil),             // 18: ai_order.CancelOrderResponse
	(*AIImpactAnalysis)(nil),                // 19: ai_order.AIImpactAnalysis
	(*GetOrderRecommendationsRequest)(nil),  // 20: ai_order.GetOrderRecommendationsRequest
	(*GetOrderRecommendationsResponse)(nil), // 21: ai_order.GetOrderRecommendationsResponse
	(*RecommendedItem)(nil),                 // 22: ai_order.RecommendedItem
	(*AnalyzeOrderPatternsRequest)(nil),     // 23: ai_order.AnalyzeOrderPatternsRequest
	(*AnalyzeOrderPatternsResponse)(nil),    // 24: ai_order.AnalyzeOrderPatternsResponse
	(*PatternInsight)(nil),                  // 25: ai_order.PatternInsight
	(*PredictCompletionTimeRequest)(nil),    // 26: ai_order.PredictCompletionTimeRequest
	(*PredictCompletionTimeResponse)(nil),   // 27: ai_order.PredictCompletionTimeResponse
	(*timestamppb.Timestamp)(nil),           // 28: google.protobuf.Timestamp
}
var file_ai_order_proto_depIdxs = []int32{
	3,  // 0: ai_order.OrderItem.ai_insights:type_name -> ai_order.AIItemInsights
	5,  // 1: ai_order.Customer.ai_profile:type_name -> ai_order.AICustomerProfile
	4,  // 2: ai_order.Order.customer:type_name -> ai_order.Customer
	2,  // 3: ai_order.Order.items:type_name -> ai_order.OrderItem
	0,  // 4: ai_order.Order.status:type_name -> ai_order.OrderStatus
	1,  // 5: ai_order.Order.priority:type_name -> ai_order.OrderPriority
	28, // 6: ai_order.Order.created_at:type_name -> google.protobuf.Timestamp
	28, // 7: ai_order.Order.updated_at:type_name -> google.protobuf.Timestamp
	28, // 8: ai_order.Order.estimated_completion:type_name -> google.protobuf.Timestamp
	7,  // 9: ai_order.Order.ai_insights:type_name -> ai_order.AIOrderInsights
	4,  // 10: ai_order.CreateOrderRequest.customer:type_name -> ai_order.Customer
	2,  // 11: ai_order.CreateOrderRequest.items:type_name -> ai_order.OrderItem
	6,  // 12: ai_order.CreateOrderResponse.order:type_name -> ai_order.Order
	6,  // 13: ai_order.GetOrderResponse.order:type_name -> ai_order.Order
	0,  // 14: ai_order.ListOrdersRequest.status:type_name -> ai_order.OrderStatus
	28, // 15: ai_order.ListOrdersRequest.from_date:type_name -> google.protobuf.Timestamp
	28, // 16: ai_order.ListOrdersRequest.to_date:type_name -> google.protobuf.Timestamp
	6,  // 17: ai_order.ListOrdersResponse.orders:type_name -> ai_order.Order
	14, // 18: ai_order.ListOrdersResponse.ai_analytics:type_name -> ai_order.AIAnalytics
	0,  // 19: ai_order.UpdateOrderStatusRequest.new_status:type_name -> ai_order.OrderStatus
	6,  // 20: ai_order.UpdateOrderStatusResponse.order:type_name -> ai_order.Order
	6,  // 21: ai_order.CancelOrderResponse.order:type_name -> ai_order.Order
	19, // 22: ai_order.CancelOrderResponse.impact_analysis:type_name -> ai_order.AIImpactAnalysis
	22, // 23: ai_order.GetOrderRecommendationsResponse.recommendations:type_name -> ai_order.RecommendedItem
	28, // 24: ai_order.AnalyzeOrderPatternsRequest.from_date:type_name -> google.protobuf.Timestamp
	28, // 25: ai_order.AnalyzeOrderPatternsRequest.to_date:type_name -> google.protobuf.Timestamp
	25, // 26: ai_order.AnalyzeOrderPatternsResponse.insights:type_name -> ai_order.PatternInsight
	28, // 27: ai_order.PredictCompletionTimeResponse.estimated_completion_time:type_name -> google.protobuf.Timestamp
	8,  // 28: ai_order.AIOrderService.CreateOrder:input_type -> ai_order.CreateOrderRequest
	10, // 29: ai_order.AIOrderService.GetOrder:input_type -> ai_order.GetOrderRequest
	12, // 30: ai_order.AIOrderService.ListOrders:input_type -> ai_order.ListOrdersRequest
	15, // 31: ai_order.AIOrderService.UpdateOrderStatus:input_type -> ai_order.UpdateOrderStatusRequest
	17, // 32: ai_order.AIOrderService.CancelOrder:input_type -> ai_order.CancelOrderRequest
	20, // 33: ai_order.AIOrderService.GetOrderRecommendations:input_type -> ai_order.GetOrderRecommendationsRequest
	23, // 34: ai_order.AIOrderService.AnalyzeOrderPatterns:input_type -> ai_order.AnalyzeOrderPatternsRequest
	26, // 35: ai_order.AIOrderService.PredictCompletionTime:input_type -> ai_order.PredictCompletionTimeRequest
	9,  // 36: ai_order.AIOrderService.CreateOrder:output_type -> ai_order.CreateOrderResponse
	11, // 37: ai_order.AIOrderService.GetOrder:output_type -> ai_order.GetOrderResponse
	13, // 38: ai_order.AIOrderService.ListOrders:output_type -> ai_order.ListOrdersResponse
	16, // 39: ai_order.AIOrderService.UpdateOrderStatus:output_type -> ai_order.UpdateOrderStatusResponse
	18, // 40: ai_order.AIOrderService.CancelOrder:output_type -> ai_order.CancelOrderResponse
	21, // 41: ai_order.AIOrderService.GetOrderRecommendations:output_type -> ai_order.GetOrderRecommendationsResponse
	24, // 42: ai_order.AIOrderService.AnalyzeOrderPatterns:output_type -> ai_order.AnalyzeOrderPatternsResponse
	27, // 43: ai_order.AIOrderService.PredictCompletionTime:output_type -> ai_order.PredictCompletionTimeResponse
	36, // [36:44] is the sub-list for method output_type
	28, // [28:36] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_ai_order_proto_init() }
func file_ai_order_proto_init() {
	if File_ai_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_order_proto_rawDesc), len(file_ai_order_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_order_proto_goTypes,
		DependencyIndexes: file_ai_order_proto_depIdxs,
		EnumInfos:         file_ai_order_proto_enumTypes,
		MessageInfos:      file_ai_order_proto_msgTypes,
	}.Build()
	File_ai_order_proto = out.File
	file_ai_order_proto_goTypes = nil
	file_ai_order_proto_depIdxs = nil
}
