// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: arbitrage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpportunityStatus represents the status of an arbitrage opportunity
type OpportunityStatus int32

const (
	OpportunityStatus_OPPORTUNITY_UNKNOWN   OpportunityStatus = 0
	OpportunityStatus_OPPORTUNITY_ACTIVE    OpportunityStatus = 1
	OpportunityStatus_OPPORTUNITY_MATCHED   OpportunityStatus = 2
	OpportunityStatus_OPPORTUNITY_EXECUTING OpportunityStatus = 3
	OpportunityStatus_OPPORTUNITY_COMPLETED OpportunityStatus = 4
	OpportunityStatus_OPPORTUNITY_EXPIRED   OpportunityStatus = 5
	OpportunityStatus_OPPORTUNITY_CANCELLED OpportunityStatus = 6
)

// ParticipantType represents the type of participant
type ParticipantType int32

const (
	ParticipantType_PARTICIPANT_UNKNOWN      ParticipantType = 0
	ParticipantType_PARTICIPANT_BUYER        ParticipantType = 1
	ParticipantType_PARTICIPANT_SELLER       ParticipantType = 2
	ParticipantType_PARTICIPANT_BOTH         ParticipantType = 3
	ParticipantType_PARTICIPANT_MARKET_MAKER ParticipantType = 4
)

// ParticipantStatus represents the status of a participant
type ParticipantStatus int32

const (
	ParticipantStatus_PARTICIPANT_STATUS_UNKNOWN              ParticipantStatus = 0
	ParticipantStatus_PARTICIPANT_STATUS_ACTIVE               ParticipantStatus = 1
	ParticipantStatus_PARTICIPANT_STATUS_INACTIVE             ParticipantStatus = 2
	ParticipantStatus_PARTICIPANT_STATUS_SUSPENDED            ParticipantStatus = 3
	ParticipantStatus_PARTICIPANT_STATUS_PENDING_VERIFICATION ParticipantStatus = 4
)

// RiskTolerance represents risk tolerance levels
type RiskTolerance int32

const (
	RiskTolerance_RISK_UNKNOWN RiskTolerance = 0
	RiskTolerance_RISK_LOW     RiskTolerance = 1
	RiskTolerance_RISK_MEDIUM  RiskTolerance = 2
	RiskTolerance_RISK_HIGH    RiskTolerance = 3
)

// OrderType represents order types
type OrderType int32

const (
	OrderType_ORDER_UNKNOWN OrderType = 0
	OrderType_ORDER_BUY     OrderType = 1
	OrderType_ORDER_SELL    OrderType = 2
	OrderType_ORDER_LIMIT   OrderType = 3
	OrderType_ORDER_MARKET  OrderType = 4
)

// ArbitrageOrderStatus represents arbitrage order status
type ArbitrageOrderStatus int32

const (
	ArbitrageOrderStatus_ORDER_STATUS_UNKNOWN   ArbitrageOrderStatus = 0
	ArbitrageOrderStatus_ORDER_STATUS_PENDING   ArbitrageOrderStatus = 1
	ArbitrageOrderStatus_ORDER_STATUS_PARTIAL   ArbitrageOrderStatus = 2
	ArbitrageOrderStatus_ORDER_STATUS_FILLED    ArbitrageOrderStatus = 3
	ArbitrageOrderStatus_ORDER_STATUS_CANCELLED ArbitrageOrderStatus = 4
	ArbitrageOrderStatus_ORDER_STATUS_REJECTED  ArbitrageOrderStatus = 5
)

// TradeStatus represents trade status
type TradeStatus int32

const (
	TradeStatus_TRADE_UNKNOWN   TradeStatus = 0
	TradeStatus_TRADE_PENDING   TradeStatus = 1
	TradeStatus_TRADE_EXECUTING TradeStatus = 2
	TradeStatus_TRADE_COMPLETED TradeStatus = 3
	TradeStatus_TRADE_FAILED    TradeStatus = 4
	TradeStatus_TRADE_CANCELLED TradeStatus = 5
)

// ArbitrageOpportunity represents an arbitrage opportunity
type ArbitrageOpportunity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AssetSymbol     string                     `protobuf:"bytes,2,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	BuyPrice        float64                    `protobuf:"fixed64,3,opt,name=buy_price,json=buyPrice,proto3" json:"buy_price,omitempty"`
	SellPrice       float64                    `protobuf:"fixed64,4,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	ProfitMargin    float64                    `protobuf:"fixed64,5,opt,name=profit_margin,json=profitMargin,proto3" json:"profit_margin,omitempty"`
	Volume          float64                    `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`
	BuyMarket       string                     `protobuf:"bytes,7,opt,name=buy_market,json=buyMarket,proto3" json:"buy_market,omitempty"`
	SellMarket      string                     `protobuf:"bytes,8,opt,name=sell_market,json=sellMarket,proto3" json:"sell_market,omitempty"`
	Status          OpportunityStatus          `protobuf:"varint,9,opt,name=status,proto3,enum=arbitrage.OpportunityStatus" json:"status,omitempty"`
	RiskScore       float64                    `protobuf:"fixed64,10,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	ConfidenceScore float64                    `protobuf:"fixed64,11,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	CreatedAt       *timestamppb.Timestamp     `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt       *timestamppb.Timestamp     `protobuf:"bytes,13,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	AiAnalysis      *AIAnalysis                `protobuf:"bytes,14,opt,name=ai_analysis,json=aiAnalysis,proto3" json:"ai_analysis,omitempty"`
	Tags            []string                   `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *ArbitrageOpportunity) Reset() {
	*x = ArbitrageOpportunity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arbitrage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArbitrageOpportunity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbitrageOpportunity) ProtoMessage() {}

func (x *ArbitrageOpportunity) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// AIAnalysis represents AI analysis data
type AIAnalysis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PricePrediction  float64  `protobuf:"fixed64,1,opt,name=price_prediction,json=pricePrediction,proto3" json:"price_prediction,omitempty"`
	VolatilityScore  float64  `protobuf:"fixed64,2,opt,name=volatility_score,json=volatilityScore,proto3" json:"volatility_score,omitempty"`
	MarketSentiment  float64  `protobuf:"fixed64,3,opt,name=market_sentiment,json=marketSentiment,proto3" json:"market_sentiment,omitempty"`
	RiskFactors      []string `protobuf:"bytes,4,rep,name=risk_factors,json=riskFactors,proto3" json:"risk_factors,omitempty"`
	Opportunities    []string `protobuf:"bytes,5,rep,name=opportunities,proto3" json:"opportunities,omitempty"`
	Recommendation   string   `protobuf:"bytes,6,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	Confidence       float64  `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
}

func (x *AIAnalysis) Reset() {
	*x = AIAnalysis{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arbitrage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIAnalysis) ProtoMessage() {}

func (x *AIAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Participant represents a market participant
type Participant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email        string                     `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Type         ParticipantType            `protobuf:"varint,4,opt,name=type,proto3,enum=arbitrage.ParticipantType" json:"type,omitempty"`
	Status       ParticipantStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=arbitrage.ParticipantStatus" json:"status,omitempty"`
	Preferences  *ParticipantPreferences    `protobuf:"bytes,6,opt,name=preferences,proto3" json:"preferences,omitempty"`
	RiskProfile  *RiskProfile               `protobuf:"bytes,7,opt,name=risk_profile,json=riskProfile,proto3" json:"risk_profile,omitempty"`
	TradingStats *TradingStats              `protobuf:"bytes,8,opt,name=trading_stats,json=tradingStats,proto3" json:"trading_stats,omitempty"`
	CreatedAt    *timestamppb.Timestamp     `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActive   *timestamppb.Timestamp     `protobuf:"bytes,10,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
}

func (x *Participant) Reset() {
	*x = Participant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arbitrage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_arbitrage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// ParticipantPreferences represents participant preferences
type ParticipantPreferences struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PreferredAssets   []string               `protobuf:"bytes,1,rep,name=preferred_assets,json=preferredAssets,proto3" json:"preferred_assets,omitempty"`
	MinProfitMargin   float64                `protobuf:"fixed64,2,opt,name=min_profit_margin,json=minProfitMargin,proto3" json:"min_profit_margin,omitempty"`
	MaxRiskScore      float64                `protobuf:"fixed64,3,opt,name=max_risk_score,json=maxRiskScore,proto3" json:"max_risk_score,omitempty"`
	MaxTradeAmount    float64                `protobuf:"fixed64,4,opt,name=max_trade_amount,json=maxTradeAmount,proto3" json:"max_trade_amount,omitempty"`
	PreferredMarkets  []string               `protobuf:"bytes,5,rep,name=preferred_markets,json=preferredMarkets,proto3" json:"preferred_markets,omitempty"`
	AutoExecute       bool                   `protobuf:"varint,6,opt,name=auto_execute,json=autoExecute,proto3" json:"auto_execute,omitempty"`
	Notifications     *NotificationSettings  `protobuf:"bytes,7,opt,name=notifications,proto3" json:"notifications,omitempty"`
}

func (x *ParticipantPreferences) Reset() {
	*x = ParticipantPreferences{}
}

func (x *ParticipantPreferences) String() string {
	return "ParticipantPreferences{}"
}

func (*ParticipantPreferences) ProtoMessage() {}

// RiskProfile represents risk profile
type RiskProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tolerance             RiskTolerance `protobuf:"varint,1,opt,name=tolerance,proto3,enum=arbitrage.RiskTolerance" json:"tolerance,omitempty"`
	MaxExposure           float64       `protobuf:"fixed64,2,opt,name=max_exposure,json=maxExposure,proto3" json:"max_exposure,omitempty"`
	DailyLimit            float64       `protobuf:"fixed64,3,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	RestrictedAssets      []string      `protobuf:"bytes,4,rep,name=restricted_assets,json=restrictedAssets,proto3" json:"restricted_assets,omitempty"`
	RequireManualApproval bool          `protobuf:"varint,5,opt,name=require_manual_approval,json=requireManualApproval,proto3" json:"require_manual_approval,omitempty"`
}

func (x *RiskProfile) Reset() {
	*x = RiskProfile{}
}

func (x *RiskProfile) String() string {
	return "RiskProfile{}"
}

func (*RiskProfile) ProtoMessage() {}

// TradingStats represents trading statistics
type TradingStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalTrades         int64                  `protobuf:"varint,1,opt,name=total_trades,json=totalTrades,proto3" json:"total_trades,omitempty"`
	TotalProfit         float64                `protobuf:"fixed64,2,opt,name=total_profit,json=totalProfit,proto3" json:"total_profit,omitempty"`
	SuccessRate         float64                `protobuf:"fixed64,3,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AverageProfitMargin float64                `protobuf:"fixed64,4,opt,name=average_profit_margin,json=averageProfitMargin,proto3" json:"average_profit_margin,omitempty"`
	TotalVolume         float64                `protobuf:"fixed64,5,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	LastTrade           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_trade,json=lastTrade,proto3" json:"last_trade,omitempty"`
}

func (x *TradingStats) Reset() {
	*x = TradingStats{}
}

func (x *TradingStats) String() string {
	return "TradingStats{}"
}

func (*TradingStats) ProtoMessage() {}

// NotificationSettings represents notification settings
type NotificationSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmailEnabled         bool    `protobuf:"varint,1,opt,name=email_enabled,json=emailEnabled,proto3" json:"email_enabled,omitempty"`
	SmsEnabled           bool    `protobuf:"varint,2,opt,name=sms_enabled,json=smsEnabled,proto3" json:"sms_enabled,omitempty"`
	PushEnabled          bool    `protobuf:"varint,3,opt,name=push_enabled,json=pushEnabled,proto3" json:"push_enabled,omitempty"`
	MinProfitThreshold   float64 `protobuf:"fixed64,4,opt,name=min_profit_threshold,json=minProfitThreshold,proto3" json:"min_profit_threshold,omitempty"`
	RealTimeAlerts       bool    `protobuf:"varint,5,opt,name=real_time_alerts,json=realTimeAlerts,proto3" json:"real_time_alerts,omitempty"`
}

func (x *NotificationSettings) Reset() {
	*x = NotificationSettings{}
}

func (x *NotificationSettings) String() string {
	return "NotificationSettings{}"
}

func (*NotificationSettings) ProtoMessage() {}

// Request/Response message types for the arbitrage service

// CreateOpportunityRequest represents a request to create an arbitrage opportunity
type CreateOpportunityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbol string   `protobuf:"bytes,1,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	BuyPrice    float64  `protobuf:"fixed64,2,opt,name=buy_price,json=buyPrice,proto3" json:"buy_price,omitempty"`
	SellPrice   float64  `protobuf:"fixed64,3,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	Volume      float64  `protobuf:"fixed64,4,opt,name=volume,proto3" json:"volume,omitempty"`
	BuyMarket   string   `protobuf:"bytes,5,opt,name=buy_market,json=buyMarket,proto3" json:"buy_market,omitempty"`
	SellMarket  string   `protobuf:"bytes,6,opt,name=sell_market,json=sellMarket,proto3" json:"sell_market,omitempty"`
	Tags        []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *CreateOpportunityRequest) Reset() {
	*x = CreateOpportunityRequest{}
}

func (x *CreateOpportunityRequest) String() string {
	return "CreateOpportunityRequest{}"
}

func (*CreateOpportunityRequest) ProtoMessage() {}

// CreateOpportunityResponse represents a response to create opportunity request
type CreateOpportunityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Opportunity *ArbitrageOpportunity `protobuf:"bytes,1,opt,name=opportunity,proto3" json:"opportunity,omitempty"`
	Success     bool                  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message     string                `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateOpportunityResponse) Reset() {
	*x = CreateOpportunityResponse{}
}

func (x *CreateOpportunityResponse) String() string {
	return "CreateOpportunityResponse{}"
}

func (*CreateOpportunityResponse) ProtoMessage() {}

// GetOpportunitiesRequest represents a request to get opportunities
type GetOpportunitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbol      string   `protobuf:"bytes,1,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	MinProfitMargin  float64  `protobuf:"fixed64,2,opt,name=min_profit_margin,json=minProfitMargin,proto3" json:"min_profit_margin,omitempty"`
	MaxRiskScore     float64  `protobuf:"fixed64,3,opt,name=max_risk_score,json=maxRiskScore,proto3" json:"max_risk_score,omitempty"`
	Limit            int32    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset           int32    `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Markets          []string `protobuf:"bytes,6,rep,name=markets,proto3" json:"markets,omitempty"`
}

func (x *GetOpportunitiesRequest) Reset() {
	*x = GetOpportunitiesRequest{}
}

func (x *GetOpportunitiesRequest) String() string {
	return "GetOpportunitiesRequest{}"
}

func (*GetOpportunitiesRequest) ProtoMessage() {}

// GetOpportunitiesResponse represents a response to get opportunities request
type GetOpportunitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Opportunities []*ArbitrageOpportunity `protobuf:"bytes,1,rep,name=opportunities,proto3" json:"opportunities,omitempty"`
	TotalCount    int32                   `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Success       bool                    `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                  `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetOpportunitiesResponse) Reset() {
	*x = GetOpportunitiesResponse{}
}

func (x *GetOpportunitiesResponse) String() string {
	return "GetOpportunitiesResponse{}"
}

func (*GetOpportunitiesResponse) ProtoMessage() {}

// Additional essential message types for the arbitrage system

// Trade represents a completed trade
type Trade struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OpportunityId string                 `protobuf:"bytes,2,opt,name=opportunity_id,json=opportunityId,proto3" json:"opportunity_id,omitempty"`
	BuyerId       string                 `protobuf:"bytes,3,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	SellerId      string                 `protobuf:"bytes,4,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	AssetSymbol   string                 `protobuf:"bytes,5,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	Quantity      float64                `protobuf:"fixed64,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	BuyPrice      float64                `protobuf:"fixed64,7,opt,name=buy_price,json=buyPrice,proto3" json:"buy_price,omitempty"`
	SellPrice     float64                `protobuf:"fixed64,8,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	Profit        float64                `protobuf:"fixed64,9,opt,name=profit,proto3" json:"profit,omitempty"`
	Status        TradeStatus            `protobuf:"varint,10,opt,name=status,proto3,enum=arbitrage.TradeStatus" json:"status,omitempty"`
	ExecutedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	SettledAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=settled_at,json=settledAt,proto3" json:"settled_at,omitempty"`
}

func (x *Trade) Reset() {
	*x = Trade{}
}

func (x *Trade) String() string {
	return "Trade{}"
}

func (*Trade) ProtoMessage() {}

var file_arbitrage_proto_msgTypes = make([]protoimpl.MessageInfo, 12)

// Additional message types needed for compilation

// ExecuteTradeRequest represents a request to execute a trade
type ExecuteTradeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpportunityId string  `protobuf:"bytes,1,opt,name=opportunity_id,json=opportunityId,proto3" json:"opportunity_id,omitempty"`
	BuyerId       string  `protobuf:"bytes,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	SellerId      string  `protobuf:"bytes,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Quantity      float64 `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64 `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	ForceExecute  bool    `protobuf:"varint,6,opt,name=force_execute,json=forceExecute,proto3" json:"force_execute,omitempty"`
}

func (x *ExecuteTradeRequest) Reset() {
	*x = ExecuteTradeRequest{}
}

func (x *ExecuteTradeRequest) String() string {
	return "ExecuteTradeRequest{}"
}

func (*ExecuteTradeRequest) ProtoMessage() {}

// ExecuteTradeResponse represents a response to execute trade request
type ExecuteTradeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trade         *Trade `protobuf:"bytes,1,opt,name=trade,proto3" json:"trade,omitempty"`
	Success       bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	TransactionId string `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
}

func (x *ExecuteTradeResponse) Reset() {
	*x = ExecuteTradeResponse{}
}

func (x *ExecuteTradeResponse) String() string {
	return "ExecuteTradeResponse{}"
}

func (*ExecuteTradeResponse) ProtoMessage() {}

// MatchParticipantsRequest represents a request to match participants
type MatchParticipantsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpportunityId  string   `protobuf:"bytes,1,opt,name=opportunity_id,json=opportunityId,proto3" json:"opportunity_id,omitempty"`
	ParticipantIds []string `protobuf:"bytes,2,rep,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	AutoExecute    bool     `protobuf:"varint,3,opt,name=auto_execute,json=autoExecute,proto3" json:"auto_execute,omitempty"`
}

func (x *MatchParticipantsRequest) Reset() {
	*x = MatchParticipantsRequest{}
}

func (x *MatchParticipantsRequest) String() string {
	return "MatchParticipantsRequest{}"
}

func (*MatchParticipantsRequest) ProtoMessage() {}

// MatchParticipantsResponse represents a response to match participants request
type MatchParticipantsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Matches []*ParticipantMatch `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	Success bool                `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message string              `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MatchParticipantsResponse) Reset() {
	*x = MatchParticipantsResponse{}
}

func (x *MatchParticipantsResponse) String() string {
	return "MatchParticipantsResponse{}"
}

func (*MatchParticipantsResponse) ProtoMessage() {}

// ParticipantMatch represents a match between buyer and seller
type ParticipantMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuyerId           string      `protobuf:"bytes,1,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	SellerId          string      `protobuf:"bytes,2,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	MatchScore        float64     `protobuf:"fixed64,3,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`
	SuggestedQuantity float64     `protobuf:"fixed64,4,opt,name=suggested_quantity,json=suggestedQuantity,proto3" json:"suggested_quantity,omitempty"`
	SuggestedPrice    float64     `protobuf:"fixed64,5,opt,name=suggested_price,json=suggestedPrice,proto3" json:"suggested_price,omitempty"`
	MatchAnalysis     *AIAnalysis `protobuf:"bytes,6,opt,name=match_analysis,json=matchAnalysis,proto3" json:"match_analysis,omitempty"`
}

func (x *ParticipantMatch) Reset() {
	*x = ParticipantMatch{}
}

func (x *ParticipantMatch) String() string {
	return "ParticipantMatch{}"
}

func (*ParticipantMatch) ProtoMessage() {}

var file_arbitrage_proto_goTypes = []interface{}{
	(*ArbitrageOpportunity)(nil),     // 0: arbitrage.ArbitrageOpportunity
	(*AIAnalysis)(nil),               // 1: arbitrage.AIAnalysis
	(*Participant)(nil),              // 2: arbitrage.Participant
	(*ParticipantPreferences)(nil),   // 3: arbitrage.ParticipantPreferences
	(*RiskProfile)(nil),              // 4: arbitrage.RiskProfile
	(*TradingStats)(nil),             // 5: arbitrage.TradingStats
	(*NotificationSettings)(nil),     // 6: arbitrage.NotificationSettings
	(*CreateOpportunityRequest)(nil), // 7: arbitrage.CreateOpportunityRequest
	(*CreateOpportunityResponse)(nil),// 8: arbitrage.CreateOpportunityResponse
	(*GetOpportunitiesRequest)(nil),  // 9: arbitrage.GetOpportunitiesRequest
	(*GetOpportunitiesResponse)(nil), // 10: arbitrage.GetOpportunitiesResponse
	(*Trade)(nil),                    // 11: arbitrage.Trade
	(*ExecuteTradeRequest)(nil),      // 12: arbitrage.ExecuteTradeRequest
	(*ExecuteTradeResponse)(nil),     // 13: arbitrage.ExecuteTradeResponse
	(*MatchParticipantsRequest)(nil), // 14: arbitrage.MatchParticipantsRequest
	(*MatchParticipantsResponse)(nil),// 15: arbitrage.MatchParticipantsResponse
	(*ParticipantMatch)(nil),         // 16: arbitrage.ParticipantMatch
}

// Market Data message types

// MarketPrice represents market price data
type MarketPrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbol string                 `protobuf:"bytes,1,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	Market      string                 `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	BidPrice    float64                `protobuf:"fixed64,3,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`
	AskPrice    float64                `protobuf:"fixed64,4,opt,name=ask_price,json=askPrice,proto3" json:"ask_price,omitempty"`
	LastPrice   float64                `protobuf:"fixed64,5,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	Volume24H   float64                `protobuf:"fixed64,6,opt,name=volume_24h,json=volume24h,proto3" json:"volume_24h,omitempty"`
	Change24H   float64                `protobuf:"fixed64,7,opt,name=change_24h,json=change24h,proto3" json:"change_24h,omitempty"`
	Timestamp   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *MarketPrice) Reset() {
	*x = MarketPrice{}
}

func (x *MarketPrice) String() string {
	return "MarketPrice{}"
}

func (*MarketPrice) ProtoMessage() {}

// GetMarketPricesRequest represents a request to get market prices
type GetMarketPricesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbols []string `protobuf:"bytes,1,rep,name=asset_symbols,json=assetSymbols,proto3" json:"asset_symbols,omitempty"`
	Markets      []string `protobuf:"bytes,2,rep,name=markets,proto3" json:"markets,omitempty"`
}

func (x *GetMarketPricesRequest) Reset() {
	*x = GetMarketPricesRequest{}
}

func (x *GetMarketPricesRequest) String() string {
	return "GetMarketPricesRequest{}"
}

func (*GetMarketPricesRequest) ProtoMessage() {}

// GetMarketPricesResponse represents a response to get market prices request
type GetMarketPricesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prices  []*MarketPrice `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	Success bool           `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message string         `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetMarketPricesResponse) Reset() {
	*x = GetMarketPricesResponse{}
}

func (x *GetMarketPricesResponse) String() string {
	return "GetMarketPricesResponse{}"
}

func (*GetMarketPricesResponse) ProtoMessage() {}

// Additional essential message types

// GetMarketAnalysisRequest represents a request for market analysis
type GetMarketAnalysisRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbol string   `protobuf:"bytes,1,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	Markets     []string `protobuf:"bytes,2,rep,name=markets,proto3" json:"markets,omitempty"`
	Timeframe   string   `protobuf:"bytes,3,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
}

func (x *GetMarketAnalysisRequest) Reset() {
	*x = GetMarketAnalysisRequest{}
}

func (x *GetMarketAnalysisRequest) String() string {
	return "GetMarketAnalysisRequest{}"
}

func (*GetMarketAnalysisRequest) ProtoMessage() {}

// GetMarketAnalysisResponse represents a response to market analysis request
type GetMarketAnalysisResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Analysis *MarketAnalysis `protobuf:"bytes,1,opt,name=analysis,proto3" json:"analysis,omitempty"`
	Success  bool            `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message  string          `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetMarketAnalysisResponse) Reset() {
	*x = GetMarketAnalysisResponse{}
}

func (x *GetMarketAnalysisResponse) String() string {
	return "GetMarketAnalysisResponse{}"
}

func (*GetMarketAnalysisResponse) ProtoMessage() {}

// MarketAnalysis represents comprehensive market analysis
type MarketAnalysis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbol        string                     `protobuf:"bytes,1,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	CurrentPrice       float64                    `protobuf:"fixed64,2,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	PredictedPrice     float64                    `protobuf:"fixed64,3,opt,name=predicted_price,json=predictedPrice,proto3" json:"predicted_price,omitempty"`
	Volatility         float64                    `protobuf:"fixed64,4,opt,name=volatility,proto3" json:"volatility,omitempty"`
	SentimentScore     float64                    `protobuf:"fixed64,5,opt,name=sentiment_score,json=sentimentScore,proto3" json:"sentiment_score,omitempty"`
	Opportunities      []*ArbitrageOpportunity    `protobuf:"bytes,6,rep,name=opportunities,proto3" json:"opportunities,omitempty"`
	RiskFactors        []string                   `protobuf:"bytes,7,rep,name=risk_factors,json=riskFactors,proto3" json:"risk_factors,omitempty"`
	SupportLevels      []*PriceLevel              `protobuf:"bytes,8,rep,name=support_levels,json=supportLevels,proto3" json:"support_levels,omitempty"`
	ResistanceLevels   []*PriceLevel              `protobuf:"bytes,9,rep,name=resistance_levels,json=resistanceLevels,proto3" json:"resistance_levels,omitempty"`
	AnalysisTime       *timestamppb.Timestamp     `protobuf:"bytes,10,opt,name=analysis_time,json=analysisTime,proto3" json:"analysis_time,omitempty"`
}

func (x *MarketAnalysis) Reset() {
	*x = MarketAnalysis{}
}

func (x *MarketAnalysis) String() string {
	return "MarketAnalysis{}"
}

func (*MarketAnalysis) ProtoMessage() {}

// PriceLevel represents a price level (support/resistance)
type PriceLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price    float64 `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Strength float64 `protobuf:"fixed64,2,opt,name=strength,proto3" json:"strength,omitempty"`
	Type     string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
}

func (x *PriceLevel) String() string {
	return "PriceLevel{}"
}

func (*PriceLevel) ProtoMessage() {}

// Additional missing message types

// OpportunityEvent represents an opportunity event
type OpportunityEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType     string                     `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Opportunity   *ArbitrageOpportunity      `protobuf:"bytes,2,opt,name=opportunity,proto3" json:"opportunity,omitempty"`
	Timestamp     *timestamppb.Timestamp     `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ParticipantId string                     `protobuf:"bytes,4,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
}

func (x *OpportunityEvent) Reset() {
	*x = OpportunityEvent{}
}

func (x *OpportunityEvent) String() string {
	return "OpportunityEvent{}"
}

func (*OpportunityEvent) ProtoMessage() {}

// PriceUpdate represents a price update
type PriceUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price      *MarketPrice           `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	UpdateType string                 `protobuf:"bytes,2,opt,name=update_type,json=updateType,proto3" json:"update_type,omitempty"`
	Timestamp  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *PriceUpdate) Reset() {
	*x = PriceUpdate{}
}

func (x *PriceUpdate) String() string {
	return "PriceUpdate{}"
}

func (*PriceUpdate) ProtoMessage() {}

// SubscribeOpportunitiesRequest represents a request to subscribe to opportunities
type SubscribeOpportunitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbols     []string `protobuf:"bytes,1,rep,name=asset_symbols,json=assetSymbols,proto3" json:"asset_symbols,omitempty"`
	MinProfitMargin  float64  `protobuf:"fixed64,2,opt,name=min_profit_margin,json=minProfitMargin,proto3" json:"min_profit_margin,omitempty"`
	Markets          []string `protobuf:"bytes,3,rep,name=markets,proto3" json:"markets,omitempty"`
	ParticipantId    string   `protobuf:"bytes,4,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
}

func (x *SubscribeOpportunitiesRequest) Reset() {
	*x = SubscribeOpportunitiesRequest{}
}

func (x *SubscribeOpportunitiesRequest) String() string {
	return "SubscribeOpportunitiesRequest{}"
}

func (*SubscribeOpportunitiesRequest) ProtoMessage() {}

// GetParticipantProfileRequest represents a request to get participant profile
type GetParticipantProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParticipantId string `protobuf:"bytes,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
}

func (x *GetParticipantProfileRequest) Reset() {
	*x = GetParticipantProfileRequest{}
}

func (x *GetParticipantProfileRequest) String() string {
	return "GetParticipantProfileRequest{}"
}

func (*GetParticipantProfileRequest) ProtoMessage() {}

// GetParticipantProfileResponse represents a response to get participant profile
type GetParticipantProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Participant *Participant `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
	Success     bool         `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message     string       `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetParticipantProfileResponse) Reset() {
	*x = GetParticipantProfileResponse{}
}

func (x *GetParticipantProfileResponse) String() string {
	return "GetParticipantProfileResponse{}"
}

func (*GetParticipantProfileResponse) ProtoMessage() {}

// UpdateParticipantPreferencesRequest represents a request to update participant preferences
type UpdateParticipantPreferencesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParticipantId string                  `protobuf:"bytes,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	Preferences   *ParticipantPreferences `protobuf:"bytes,2,opt,name=preferences,proto3" json:"preferences,omitempty"`
}

func (x *UpdateParticipantPreferencesRequest) Reset() {
	*x = UpdateParticipantPreferencesRequest{}
}

func (x *UpdateParticipantPreferencesRequest) String() string {
	return "UpdateParticipantPreferencesRequest{}"
}

func (*UpdateParticipantPreferencesRequest) ProtoMessage() {}

// UpdateParticipantPreferencesResponse represents a response to update participant preferences
type UpdateParticipantPreferencesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateParticipantPreferencesResponse) Reset() {
	*x = UpdateParticipantPreferencesResponse{}
}

func (x *UpdateParticipantPreferencesResponse) String() string {
	return "UpdateParticipantPreferencesResponse{}"
}

func (*UpdateParticipantPreferencesResponse) ProtoMessage() {}

// HistoricalPrice represents historical price data
type HistoricalPrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Open      float64                `protobuf:"fixed64,2,opt,name=open,proto3" json:"open,omitempty"`
	High      float64                `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Low       float64                `protobuf:"fixed64,4,opt,name=low,proto3" json:"low,omitempty"`
	Close     float64                `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	Volume    float64                `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *HistoricalPrice) Reset() {
	*x = HistoricalPrice{}
}

func (x *HistoricalPrice) String() string {
	return "HistoricalPrice{}"
}

func (*HistoricalPrice) ProtoMessage() {}

// OrderBookLevel represents an order book level
type OrderBookLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price      float64 `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity   float64 `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderCount int32   `protobuf:"varint,3,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
}

func (x *OrderBookLevel) Reset() {
	*x = OrderBookLevel{}
}

func (x *OrderBookLevel) String() string {
	return "OrderBookLevel{}"
}

func (*OrderBookLevel) ProtoMessage() {}

// SubscribePricesRequest represents a request to subscribe to price updates
type SubscribePricesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbols  []string `protobuf:"bytes,1,rep,name=asset_symbols,json=assetSymbols,proto3" json:"asset_symbols,omitempty"`
	Markets       []string `protobuf:"bytes,2,rep,name=markets,proto3" json:"markets,omitempty"`
	ParticipantId string   `protobuf:"bytes,3,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
}

func (x *SubscribePricesRequest) Reset() {
	*x = SubscribePricesRequest{}
}

func (x *SubscribePricesRequest) String() string {
	return "SubscribePricesRequest{}"
}

func (*SubscribePricesRequest) ProtoMessage() {}

// GetHistoricalDataRequest represents a request for historical data
type GetHistoricalDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbol string                 `protobuf:"bytes,1,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	Market      string                 `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	StartTime   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Interval    string                 `protobuf:"bytes,5,opt,name=interval,proto3" json:"interval,omitempty"`
}

func (x *GetHistoricalDataRequest) Reset() {
	*x = GetHistoricalDataRequest{}
}

func (x *GetHistoricalDataRequest) String() string {
	return "GetHistoricalDataRequest{}"
}

func (*GetHistoricalDataRequest) ProtoMessage() {}

// GetHistoricalDataResponse represents a response for historical data
type GetHistoricalDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prices  []*HistoricalPrice `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	Success bool               `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message string             `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetHistoricalDataResponse) Reset() {
	*x = GetHistoricalDataResponse{}
}

func (x *GetHistoricalDataResponse) String() string {
	return "GetHistoricalDataResponse{}"
}

func (*GetHistoricalDataResponse) ProtoMessage() {}

// GetMarketDepthRequest represents a request for market depth
type GetMarketDepthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbol string `protobuf:"bytes,1,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	Market      string `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Depth       int32  `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
}

func (x *GetMarketDepthRequest) Reset() {
	*x = GetMarketDepthRequest{}
}

func (x *GetMarketDepthRequest) String() string {
	return "GetMarketDepthRequest{}"
}

func (*GetMarketDepthRequest) ProtoMessage() {}

// GetMarketDepthResponse represents a response for market depth
type GetMarketDepthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bids    []*OrderBookLevel `protobuf:"bytes,1,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks    []*OrderBookLevel `protobuf:"bytes,2,rep,name=asks,proto3" json:"asks,omitempty"`
	Success bool              `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message string            `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetMarketDepthResponse) Reset() {
	*x = GetMarketDepthResponse{}
}

func (x *GetMarketDepthResponse) String() string {
	return "GetMarketDepthResponse{}"
}

func (*GetMarketDepthResponse) ProtoMessage() {}

func init() { file_arbitrage_proto_init() }
func file_arbitrage_proto_init() {
	if File_arbitrage_proto != nil {
		return
	}
	// Implementation would continue...
}

var File_arbitrage_proto protoreflect.FileDescriptor
