# Prometheus Configuration for Developer DAO Platform
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Bounty Service metrics
  - job_name: 'bounty-service'
    static_configs:
      - targets: ['bounty-service:8080']
    scrape_interval: 10s
    metrics_path: /metrics

  # Marketplace Service metrics
  - job_name: 'marketplace-service'
    static_configs:
      - targets: ['marketplace-service:8081']
    scrape_interval: 10s
    metrics_path: /metrics

  # Metrics Service metrics
  - job_name: 'metrics-service'
    static_configs:
      - targets: ['metrics-service:8082']
    scrape_interval: 10s
    metrics_path: /metrics

  # DAO Governance Service metrics
  - job_name: 'dao-governance-service'
    static_configs:
      - targets: ['dao-governance-service:8084']
    scrape_interval: 10s
    metrics_path: /metrics

  # PostgreSQL metrics (if postgres_exporter is available)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis metrics (if redis_exporter is available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Qdrant metrics
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    scrape_interval: 30s
    metrics_path: /metrics

  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
