apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: go-coffee-production
  annotations:
    config.kubernetes.io/local-config: "true"

# Base configuration
bases:
- ../../base

# Namespace override
namespace: go-coffee-prod

# Production-specific labels
commonLabels:
  environment: production
  tier: production

# Production images with specific tags
images:
- name: ghcr.io/dimajoyti/go-coffee/user-gateway
  newTag: v1.0.0
- name: ghcr.io/dimajoyti/go-coffee/security-gateway
  newTag: v1.0.0
- name: ghcr.io/dimajoyti/go-coffee/web-ui-backend
  newTag: v1.0.0

# Production-specific ConfigMaps
configMapGenerator:
- name: go-coffee-prod-config
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=warn
  - METRICS_ENABLED=true
  - HEALTH_CHECK_INTERVAL=60s
  - RATE_LIMIT_ENABLED=true
  - WAF_ENABLED=true
  behavior: merge

# Production-specific Secrets
secretGenerator:
- name: go-coffee-prod-secrets
  files:
  - production.env
  type: Opaque
  options:
    disableNameSuffixHash: true

# Production-specific patches
patches:
# Increase replicas for production
- target:
    kind: Deployment
    name: user-gateway
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3

- target:
    kind: Deployment
    name: security-gateway
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3

- target:
    kind: Deployment
    name: web-ui-backend
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3

- target:
    kind: Deployment
    name: api-gateway
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3

# Increase resource limits for production
- target:
    kind: Deployment
    labelSelector: "app.kubernetes.io/component=gateway,app.kubernetes.io/component=security,app.kubernetes.io/component=backend"
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "512Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "500m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "256Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "200m"

# Production HPA settings
- target:
    kind: HorizontalPodAutoscaler
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 3
    - op: replace
      path: /spec/maxReplicas
      value: 20

# Production storage settings
- target:
    kind: PersistentVolumeClaim
    name: postgres-pvc
  patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: "50Gi"
    - op: replace
      path: /spec/storageClassName
      value: "fast-ssd"

- target:
    kind: PersistentVolumeClaim
    name: redis-pvc
  patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: "10Gi"
    - op: replace
      path: /spec/storageClassName
      value: "fast-ssd"

# Production ingress settings
- target:
    kind: Ingress
    name: go-coffee-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: "api.go-coffee.com"
    - op: add
      path: /metadata/annotations/cert-manager.io~1cluster-issuer
      value: "letsencrypt-prod"
    - op: add
      path: /spec/tls
      value:
      - hosts:
        - api.go-coffee.com
        secretName: go-coffee-tls

# Production service type
- target:
    kind: Service
    name: api-gateway-service
  patch: |-
    - op: replace
      path: /spec/type
      value: "LoadBalancer"
    - op: add
      path: /metadata/annotations/service.beta.kubernetes.io~1aws-load-balancer-type
      value: "nlb"

# Name suffix for production
nameSuffix: "-prod"
