apiVersion: v1
kind: Secret
metadata:
  name: go-coffee-secrets
  namespace: go-coffee
  labels:
    app.kubernetes.io/name: go-coffee
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  # Default values - CHANGE IN PRODUCTION!
  POSTGRES_PASSWORD: Z29fY29mZmVlX3Bhc3N3b3Jk  # go_coffee_password
  JWT_SECRET_KEY: c3VwZXJfc2VjcmV0X2p3dF9rZXlfY2hhbmdlX2luX3Byb2R1Y3Rpb24=  # super_secret_jwt_key_change_in_production
  REDIS_PASSWORD: ""  # Empty for development
  
  # API Keys (base64 encoded)
  BRIGHT_DATA_API_KEY: ""  # Add your Bright Data API key
  GEMINI_API_KEY: ""  # Add your Gemini API key
  TELEGRAM_BOT_TOKEN: ""  # Add your Telegram bot token
  
  # Solana Configuration
  SOLANA_PRIVATE_KEY: ""  # Add your Solana private key
  SOLANA_RPC_URL: aHR0cHM6Ly9hcGkubWFpbm5ldC1iZXRhLnNvbGFuYS5jb20=  # https://api.mainnet-beta.solana.com

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: go-coffee
  labels:
    app.kubernetes.io/name: go-coffee
    app.kubernetes.io/component: database
type: Opaque
data:
  # PostgreSQL specific secrets
  POSTGRES_USER: Z29fY29mZmVlX3VzZXI=  # go_coffee_user
  POSTGRES_PASSWORD: Z29fY29mZmVlX3Bhc3N3b3Jk  # go_coffee_password
  POSTGRES_DB: Z29fY29mZmVl  # go_coffee

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: go-coffee
  labels:
    app.kubernetes.io/name: go-coffee
    app.kubernetes.io/component: cache
type: Opaque
data:
  # Redis specific secrets
  REDIS_PASSWORD: ""  # Empty for development - set in production
