apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui-backend
  namespace: go-coffee
  labels:
    app.kubernetes.io/name: web-ui-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: go-coffee
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-ui-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-ui-backend
        app.kubernetes.io/component: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: web-ui-backend
        image: ghcr.io/dimajoyti/go-coffee/web-ui-backend:latest
        ports:
        - containerPort: 8090
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: go-coffee-config
              key: WEB_UI_BACKEND_PORT
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: go-coffee-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: go-coffee-config
              key: LOG_LEVEL
        - name: BRIGHT_DATA_API_KEY
          valueFrom:
            secretKeyRef:
              name: go-coffee-secrets
              key: BRIGHT_DATA_API_KEY
              optional: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: web-ui-backend-service
  namespace: go-coffee
  labels:
    app.kubernetes.io/name: web-ui-backend
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: web-ui-backend

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-ui-backend-hpa
  namespace: go-coffee
  labels:
    app.kubernetes.io/name: web-ui-backend
    app.kubernetes.io/component: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-ui-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
